### ISSUE TITLE
Ghost Towns

### ISSUE THREAD

**Issue by Vetrnn** [NebulaMC-GG/Support#1022]
An issue that I have come across a while back, is that towns don't appear as a town when searched using /t info [Town]. As in this example, we are using TeamAquaPlus. It gives me an error when searching it with /t info: 
![image](https://user-images.githubusercontent.com/78167145/108914949-23555200-75fa-11eb-99aa-e2ae22ddafd8.png)

Despite that, it still registers as a town as seen in the picture below. It is still claim, and not accessible by normal players There are plenty of towns like this one, so its not a 1 time issue. What I think is important to add, is that they are easily spotable because of their color. Instead of having a normal color as most towns have, its plain white.
![image](https://user-images.githubusercontent.com/78167145/108915021-42ec7a80-75fa-11eb-8428-e33baad538b2.png)

**Comment by Rasgnarok** [comment]
This will be fixed by moving to GriefDefender, they have more robust towns. Closing.
