### ISSUE TITLE
Command /Outpost List no longer works for me

### ISSUE THREAD

**Issue by HunterWulfstern** [NebulaMC-GG/Support#1142]
The command /Outpost List no longer works for me as it encounters a bug/command issue where its failed to execute it. Other players have reported it works fine for them.

I have attached a screenshot with the error message that occurs when I enter the command.

https://discord.com/channels/151095626916954113/184700717456556032/852660179132481566

If it the link does`nt work, I can resubmit it

**Comment by Vohras2** [comment]
Does this still not work? Did you have an outpost in the nether?

**Comment by HunterWulfstern** [comment]
Before the Nether was reset, I did have an outpost in the nether though it was only one.

When I do try to use the /outposts list command it comes up with the error saying unable to excute java script or something along thoses lines.

**Comment by Rasgnarok** [comment]
This will be fixed by moving to GriefDefender, closing.
