### ISSUE TITLE
Able to PVP through /pvp toggled off

### ISSUE THREAD

**Issue by SmodJah** [NebulaMC-GG/Support#1154]
While Testing, PJ was able to kill me while my PVP was toggled off, he was using an axe, he could kill me, we managed to do this continuously despite both having it toggled off, if it matters, we were both in ultra space.

https://github.com/ObliqueNET/Server/issues/1146 - PVP still possible with fists, fishing rods and other items. It doesn't do damage, but can still knock back the player. (Merge from Voh)

**Comment by Rasgnarok** [comment]
Is this still possible? There was a patch in early July applied.

**Comment by SmodJah** [comment]
Yes it is still possible, after more testing it seems like if one player has pvp enabled, sometimes they are able to hit and damage players who do not have pvp enabled. Also sometimes when disabling pvp, you will still be able to damage players afterwards.

**Comment by Rasgnarok** [comment]
This will need testing on 1.16.5, keeping this open until we can - we will have a new plugin for this.

**Comment by Rasgnarok** [comment]
Closing, a completely new plugin will have to be written now.
