### ISSUE TITLE
Aqua Skills (Swordsman/wizard/warlock) exp bug

### ISSUE THREAD

**Issue by itanomaly** [NebulaMC-GG/Support#1224]
Hi. I encountered a bug with the aqua skills system. Until I die, everything works fine. I get the swordsman exp as expected, and the wizard and warlock skills work as intended - when they hit a target they give 10 additional exp. After I die, I no longer get swordsman exp, and the wizard/warlock skills no longer give you the additional 10 exp (the projectiles aren't firing). This can be fixed by relogging. I didn't include screens of the wizard/warlock skills because it's hard to see.

<details>
<summary>Before dying, working as intended</summary>

![2022-01-16_14 53 01](https://user-images.githubusercontent.com/75062469/149660981-4abb23ed-802e-4acf-b307-06ec8580a1a4.png)

</details>

<details>
<summary>Dying</summary>

![2022-01-16_14 54 28](https://user-images.githubusercontent.com/75062469/149661017-76c794c0-fc67-43e4-adea-726514ea7616.png)

</details>

<details>
<summary>No longer working, after dying</summary>

![2022-01-16_14 54 33](https://user-images.githubusercontent.com/75062469/149661025-807bc6d4-fc5a-474c-b6bc-e9edfd4dbe22.png)

</details>

**Comment by Rasgnarok** [comment]
This will need testing on 1.16.5, keeping this open until we can.

**Comment by Rasgnarok** [comment]
Closing, AquaSkills requires a full rewrite, pending its author.
