### ISSUE TITLE
Gym Challenge/Egg Issue

### ISSUE THREAD

**Issue by chrisdurocher** [NebulaMC-GG/Support#1229]
have noticed several times now: if i accept a gym challenge with eggs in my party, sometimes they just disappear into the shadow realm never to be seen again.

For example: Generally i will have my volcarona and 5 eggs in my party, I accpet the gym challenge. After the battle I return to my pc to withdraw said pokemon and eggs and there will be only 1 or 2 eggs missing even though there is plenty of open space in pc.

Update: egg was found in pc after logging back in a couple hours later.

**Comment by Rasgnarok** [comment]
This needs testing in 1.16.5, keeping this open until we can.

**Comment by Rasgnarok** [comment]
Closing, we will not be using AquaGyms in 1.16.5 anyways.
