### ISSUE TITLE
Quest textured Pokemon broken

### ISSUE THREAD

**Issue by Izayoi-Aki** [NebulaMC-GG/Support#1232]
I did the quest Zero Hour and the Vikavolt from the quest his the custom texture in its party sprite, but upon sending the Pokemon out, the texture does not show. 

I have the most recent version of the Oblique texture pack installed.
I mentioned this to PrimalCyndaquil in game and they requested I make a ticket here about it. They said it broke due to a Pixelmon update and would require someone to make a new custom texture for it.

Thank you for your time in reading this.

**Comment by Rasgnarok** [comment]
This is probably still required from our quest team, keeping this open for a re-texture once quests are back up.

**Comment by Rasgnarok** [comment]
This now works with new 1.16.5 asset handling, closing.
