### ISSUE TITLE
NPC Voucher issue

### ISSUE THREAD

**Issue by Menno165** [NebulaMC-GG/Support#1233]
I have heard of 2 players that they had an issue with placing NPC voucher, as soon as they are placed they disappear.

A player having this issue is Redrex93, he said he won a NPC voucher, placed it, and it disappeared.

This is something that needed to be looked into.

**Comment by Rasgnarok** [comment]
Will need testing on 1.16.5, keeping this open.

**Comment by Rasgnarok** [comment]
Closing, NPC vouchers are not handled this way anymore.
