### ISSUE TITLE
Small bug: eldritch blast damaging pokemon that are not battling

### ISSUE THREAD

**Issue by redx10** [NebulaMC-GG/Support#1236]
There is a small bug with eldritch blast. When you use it facing a pokemon that is outside battle, it damage it. This only works outside of battle, but does usually provoke the pokemon to attack.  It does provoke player pokemon into attacking, but they will be stopped by the "accept battle" screen. 

My ign is Valirus, Hope this helps!

**Comment by Rasgnarok** [comment]
Closing, AquaSkills is pending a rewrite.
