### ISSUE TITLE
Discord unban

### ISSUE THREAD

**Issue by Hanahimee** [NebulaMC-GG/Support#1251]
I got banned a while ago from the discord, because of personal issues between me and Ras last year. It's been a while now and I don't think the ban should still stand. I apologize.

DC: 하나#1111

**Comment by fatyg5** [comment]
There is no ban on our Discord with that username. Are you sure you have the correct one?

**Comment by fatyg5** [comment]
Closing due to no reply. Open a new issue if needed.
