### ISSUE TITLE
Hub Scavenger Hunt

### ISSUE THREAD

**Issue by starwarschamp4** [NebulaMC-GG/Support#1266]
The head at -37 79 50 doesn't work, there is only 19/20 heads (I checked my coords on them), and when you click the first one it says that there are 21 left when there are only 20 heads.

**Comment by mnky-frt** [comment]
![image](https://user-images.githubusercontent.com/85257491/177253032-fceaadf0-68c3-41af-b7c9-be36c7e8dce3.png)
I am also having this issue with this galaxy ball i posted a screenshot

**Comment by HackuJacku** [comment]
Hello, this is now fixed :)
