### ISSUE TITLE
Minor Loot Issue

### ISSUE THREAD

**Issue by ColTheFurret** [NebulaMC-GG/Support#1271]
I RTP'd in Orion after leaving to wilderness and went to get a Pokeloot, I opened it and it said I got a "Flying Gem," but in turn I got a Dark Gem instead.
![Screenshot_3](https://user-images.githubusercontent.com/83987372/171988142-5344e71c-62d7-4a5f-bb25-19b9ab30f4b6.png)
![Screenshot_4](https://user-images.githubusercontent.com/83987372/171988147-a8a95de2-e521-4ec3-aea4-b73bedb9824b.png)

**Comment by Rasgnarok** [comment]
Can I have your mod list please, and are there any other misplaced items?

**Comment by ColTheFurret** [comment]
Yes, I'll get my modslist, and other items seems to be okay for working. Only the Gems seems to be my current noticeable thing, cause I got a "Bug Gem" Twice yesterday, but it gave Grass Gems instead in normal pokeloots later on Titan too. I don't have the Bug-Grass Gems on screenshot but the mods should be this.
![Screenshot_5](https://user-images.githubusercontent.com/83987372/172007067-ee359dcb-4155-430e-8f7b-a2bd8b97bef6.png)

**Comment by Rasgnarok** [comment]
This should now be fixed, closing.
