### ISSUE TITLE
Crate Typos

### ISSUE THREAD

**Issue by TheArkJester** [NebulaMC-GG/Support#1272]
Some of the Explores say Exploure not sure if its a typo but some are Explore and others are not
![2022-06-04_02 52 27](https://user-images.githubusercontent.com/84147710/171988306-3d0ffe73-6dd7-4d2f-8fd9-f3656dfcd3ff.png)
.

**Comment by TheArkJester** [comment]
Cosmetic is the other one that has it

**Comment by Rasgnarok** [comment]
Found it, fixing.
