### ISSUE TITLE
Galaxy ball hunt issue

### ISSUE THREAD

**Issue by Goeategg** [NebulaMC-GG/Support#1277]
While I was hunting for the galaxy balls I found one that whenever I click on it it says “Owner: unknown” this bugged ball is at X:-38 Y:79 Z:50

**Comment by Rasgnarok** [comment]
Duplicate of https://github.com/NebulaMC-GG/Support/issues/1273 - or are they different heads @ Hacko

**Comment by starwarschamp4** [comment]
Same head, original ticket is [#1266 ](https://github.com/NebulaMC-GG/Support/issues/1266)

**Comment by Rasgnarok** [comment]
Closing, duplicate.
