### ISSUE TITLE
Catch Rate Inconsistency

### ISSUE THREAD

**Issue by ThirstyMichael** [NebulaMC-GG/Support#1278]
in every generation Quick Ball is in, it has 100% catch rate against Ralts sub level 20, and I've failed first turn on 3 unique Ralts encounters

**Comment by CenizaRey** [comment]
All of the information I’m seeing regarding catch rates tells me that level isn’t a factor. Are you sure this report is accurate?

**Comment by Rasgnarok** [comment]
Currently an open bug report with PixelmonMod itself, https://pixelmonmod.com/tracker.php?p=2&t=17547

**Comment by ThirstyMichael** [comment]
> All of the information I’m seeing regarding catch rates tells me that level isn’t a factor. Are you sure this report is accurate?

I just mentioned because it used to be relevant in gen 1-2 and I didn't know it changed, thanks for pointing that out, but the issue is still that the capture failing should be impossible

**Comment by Rasgnarok** [comment]
https://github.com/NebulaMC-GG/Support/issues/1627

**Comment by Rasgnarok** [comment]
Closing, duplicate.
