### ISSUE TITLE
Spam on rtp

### ISSUE THREAD

**Issue by FBIAgentTimmy** [NebulaMC-GG/Support#1280]
fix spam on rtp - doughnutchicken from last night.

**Comment by Rasgnarok** [comment]
Fixed, rtp or rt is now on a 60s cooldown.

**Comment by UnknownFlash** [comment]
Simply put, /rtp still has a 5 second cooldown. ![image](https://user-images.githubusercontent.com/72431971/172045191-70112deb-5434-4afe-9431-0a91120b8efa.png)
