### ISSUE TITLE
Item variant mismatch in loot chat strings?

### ISSUE THREAD

**Issue by Toby-Wilson** [NebulaMC-GG/Support#1282]
just a small one, but when looting from an ultraball pokeloot (and receiving a move gem)

the chat logged i had looted a steel type gem, when I had received a fairy type gem.

**Comment by Menno165** [comment]
Looking at the time this has been reported I would assume serene seasons had something to do with this.
Since that has been removed this issue should not be happening anymore and here for we will be closing the issue.

If this does still occur feel free to re-open the issue.
