### ISSUE TITLE
Cannot connect to servers

### ISSUE THREAD

**Issue by taurosmc** [NebulaMC-GG/Support#1287]
I am getting the following error when joining any of the servers:

Internal Exception: io.netty.handler.codec.DecoderException: java.io.IOException: Payload may not be larger than 1048576 bytes

![unknown](https://user-images.githubusercontent.com/106874987/172020849-1f7a4c49-b2c0-47d5-ae31-b845dfe28542.png)

**Comment by fatyg5** [comment]
Fixed, thanks for the report.
