### ISSUE TITLE
Ocean Pokemon Spawns

### ISSUE THREAD

**Issue by JustTooSly** [NebulaMC-GG/Support#1289]
Howdy there peeps,
A few pokemon appear to be leaving the ocean and reaching up to  mach 10 speeds once they hit land. I've seen a Walmer & Clobbopus so far do this. 

Thanks

**Comment by GracieTheLatias** [comment]
Yeah this is a pixelmon mod issue, not a Nebula issue. Not sure if it was already reported on the pixelmon tracker.

**Comment by fatyg5** [comment]
Pixelmon known issue, reported to them already! Thank you for your report!
