### ISSUE TITLE
Vote crate not giving Galarica Cuff (Atlas)

### ISSUE THREAD

**Issue by DaKingOfTheDinos** [NebulaMC-GG/Support#1294]
So I was opening up a few vote crates and in one of them I won a Galarica Cuff and the crate did not give it to me even though my inventory was not full. ![2022-06-04_16 19 51](https://user-images.githubusercontent.com/106892040/172028657-db2b7982-b988-4112-bede-97fbe5a6dc69.png)
![2022-06-04_16 24 50](https://user-images.githubusercontent.com/106892040/172028658-ec49ad50-c5ee-4234-bd16-f74ea2093f9a.png)

**Comment by Rasgnarok** [comment]
Fixed, thank you!
