### ISSUE TITLE
Vote Crate gives ordinary Dragon Scale instead of 1 Specific IVs Modifier

### ISSUE THREAD

**Issue by QuinnActually** [NebulaMC-GG/Support#1295]
Rolled a Vote Crate in front of Ras while testing, got an IV Modifier (image attached); got a vanilla dragon scale instead.
![image](https://user-images.githubusercontent.com/55411824/172028860-f8f36200-b018-4f92-9fb0-bfbdb65ee96d.png)
![image](https://user-images.githubusercontent.com/55411824/172028866-2212b685-44c0-42ef-8d4f-068e4730ea9f.png)

**Comment by QuinnActually** [comment]
![image](https://user-images.githubusercontent.com/55411824/172028978-25cbe089-3389-4083-ad64-add7687eb4bb.png)
Followup: I feel it's worth noting that the item representing the voucher isn't even a Dragon Scale, and nothing on the page is a Dragon Scale either.

**Comment by fatyg5** [comment]
Should be fixed once IV modifiers are readded to crates. Thank you for the report
