### ISSUE TITLE
Mareep cant be sheer'ed.

### ISSUE THREAD

**Issue by FBIAgentTimmy** [NebulaMC-GG/Support#1300]
yes mareep cannot

**Comment by Menno165** [comment]
After some testing on the servers and singleplayer I can say that you are able to use a shear on Mareep for wool.
You do however need to catch it first, this is also the case on singleplayer.

Reading from the Pixelmon tracker below it is meant to be this way. 
https://pixelmonmod.com/tracker.php?p=2&t=13893
