### ISSUE TITLE
Vote Crate (Didn't get the Item)

### ISSUE THREAD

**Issue by KoreanNino** [NebulaMC-GG/Support#1306]
![2022-06-04_22 46 31](https://user-images.githubusercontent.com/106900561/172037342-f2253ae3-0525-4868-99e6-427b3256be03.png)
![2022-06-04_22 46 34](https://user-images.githubusercontent.com/106900561/172037344-21cc1224-8c05-47ea-809c-6a8b89c73339.png)
Didn't get my reward from the vote crate.

**Comment by doughychicken** [comment]
what is your ign

**Comment by MissElyri** [comment]
@KoreanNino  Did you get refunded? I see you were asked for an ign earlier but I'm unaware if anyone else has reached out to you about this yet.

**Comment by Rasgnarok** [comment]
It says it right there on the chat, 'KoreanNino'

**Comment by KoreanNino** [comment]
No, I haven't gotten refunded for the key yet.

**Comment by MissElyri** [comment]
Just refunded.
