### ISSUE TITLE
/echest deleted items

### ISSUE THREAD

**Issue by lolanonymous** [NebulaMC-GG/Support#1307]
/echest is deleting everything stored in it, either between server crashes or disconnects.

Items I have lost in my most recent wipe are effectively all 3 of the omen kits (initial, quarterly, and weekly).

**Comment by lolanonymous** [comment]
Upon further testing it deletes the chest upon death.

Recreating it is quite simple, just put something in enderchest and then /suicide

**Comment by Rasgnarok** [comment]
Apologies for the wait, a moderator+ will be refunding them soon. Please comment back if you can with your username and server you play on.
