### ISSUE TITLE
lost 4 vote keys on rollback

### ISSUE THREAD

**Issue by Qaz1337** [NebulaMC-GG/Support#1309]
voted on all sites and got keys but then server crashed and i kept only 2 keys
ign: soypatoshido
server: orion

(orion been crashing 7 times in 2 hours now)

**Comment by Qaz1337** [comment]
update: i used my 2 keys and got loot from one only so i lost 5 keys in total, crates might be bugged if it eats keys but dosent give loot always

**Comment by fatyg5** [comment]
DM me on Discord next time you are on, I will refund them.
