### ISSUE TITLE
No Item from Vote Crate :(

### ISSUE THREAD

**Issue by TrinaXox2** [NebulaMC-GG/Support#1310]
https://user-images.githubusercontent.com/106904622/172041145-84d172a0-433d-462e-b7d7-7bdb7609777a.png

**Comment by PenginKami** [comment]
![hmm](https://user-images.githubusercontent.com/96862959/172042329-ebbf12f8-fe16-498a-894d-cc28157bbfec.png)
Was bout to make a ticket for the chat broadcast. But I'll post it here instead lol

**Comment by HackuJacku** [comment]
This is now fixed, thank you for the report :)
