### ISSUE TITLE
Voting

### ISSUE THREAD

**Issue by Geordiebrett** [NebulaMC-GG/Support#1312]
Hi to who sees this.
 I did my 5 daily votes and all of them said thanks for voting but i never received either vote keys or the money. I tried leaving the server and joining back and still no luck. Lastly i tried re-voting incase it never registered on each site to which the prompt i got was sorry you have voted for the day. 

I voted yesterday to which i only got money but the vote keys wasnt set up then which is understandable. But they have been today as i have seen people receive them in chat.

Thank you in advance to whoever can help me with my query

Ign: Geordiebrett
Diacord: Geordiebrett

**Comment by benb25504** [comment]
I am having a similar issue: yesterday when voting I received only money and no key, and today, it didn't even register a "thanks for voting" message on the server.

**Comment by PrimalCyndaquil** [comment]
If neither of you have been refunded yet, please DM me on discord @PrimalCyndaquil#8880 with your IGN and the server you play on. This issue has since been fixed.
