### ISSUE TITLE
EChest deleted my items

### ISSUE THREAD

**Issue by UncleanCreams23** [NebulaMC-GG/Support#1314]
So I found out the hard way if you die with items in your /ec they get deleted.
I lost my master ball from jade monthly, about 25 ultraballs, 15 or so quick balls, 16 dusk balls, a bunch of pokeballs, 4 wishing pieces, my exp all, eff5 unb 3 pick, eff 4 shovel, 3 pcs, a ha lure, and a few other items I can't remember while typing this. Any chance I can get those items back ? Kinda missing the exp all the most

**Comment by Rasgnarok** [comment]
Apologies for the wait, a moderator+ will be refunding them soon. Please comment back if you can with your username and server you play on.

**Comment by UncleanCreams23** [comment]
Issue was resolved by faty (I think) I got items refunded a while back ty tho
