### ISSUE TITLE
Breeders broken

### ISSUE THREAD

**Issue by UncleanCreams23** [NebulaMC-GG/Support#1315]
My breeders currently have no pokemon in them but it's saying 0 pokemon inside ranches, remove one to add more- could it be that ranks don't have permission to add more pokemon to ranches. That being said is there any chance ranks get more available slots for pokemon now that /breed doesn't work. 
![Snapchat-1000862787](https://user-images.githubusercontent.com/104040779/172053363-8df1df24-d5ec-4386-851b-a1c6e553c5eb.jpg)
Sorry for bad picture

**Comment by fatyg5** [comment]
Fixed. Due to a weird issue with LP not inheriting perms. Still needs further investigation, but this issue is fixed.
