### ISSUE TITLE
Duping cleaned fossils 

### ISSUE THREAD

**Issue by EpicBrandonAndBlizzard** [NebulaMC-GG/Support#1318]
So I tried cleaning my fossil, apparently it's disabled? But it still cleaned it without any animations. I got it, then I tried to place it in the tank that makes the fossil into a pokemon. That as well, as no animations. So I right clicked it to get it back and kept giving me extras. I have a video of it below.
Edit: The fossil tank just keeps giving me them with an empty hand as well.

https://user-images.githubusercontent.com/106925279/172062322-1622eced-f2a2-402d-a8db-14178827d887.mp4

**Comment by EpicBrandonAndBlizzard** [comment]
I tossed them into lava after the video.

**Comment by fatyg5** [comment]
Disabled until fixed! Thank you for the report
