### ISSUE TITLE
Ekans giving 45 Speed EVs.

### ISSUE THREAD

**Issue by mosbuttpirate** [NebulaMC-GG/Support#1320]
Leveling in a Savanna using a Mareanie (Slot 1) holding a Lucky Egg and an Aerodactly (Slot 3) holding EXP Share. After about 15 kills of Attack EV Pokemon both got to max Speed EVs. Attempted to replicate with Popplio (Slot 2) holding Lucky Egg and Magikarp (Slot 4) holding EXP Share but did not observe Speed EV gain. Put Lucky egg back on Mareanie and killed an Ekans and Magikarp gained 48 Speed EVs from a battle. Took lucky egg off and killed a Patrat and no EV increase. Killed an Ekans and gained 45 Speed EVs. Switched to Popplio (Lucky Egg)and killed Ekans gaining 45 Speed EVs. Tested in single player to determine if the bug was from the mod or server. Ekans gave no Speed EVs, though I should not they were spawned from a spawner and not natural spawns, in case it may be relevant.

**Comment by Menno165** [comment]
Closing the ticket as it no longer is a issue.
It now gives naturally 1 attack evs.

If it happens again feel free to open the ticket again.
