### ISSUE TITLE
/vote GUI has a bugged extra entry

### ISSUE THREAD

**Issue by QuinnActually** [NebulaMC-GG/Support#1326]
Doing /vote yields this new button in addition to the previously existing ones:
![image](https://user-images.githubusercontent.com/55411824/172069711-c54913fd-50be-4724-aac4-0a5b7b8d7798.png)
When clicked, all that appears in chat is this:
![image](https://user-images.githubusercontent.com/55411824/172069724-4493cb33-5ce8-4760-95cf-f96bc6f32a36.png)
Clicking on this text yields this:
![image](https://user-images.githubusercontent.com/55411824/172069748-a09afe5d-c1aa-425a-bb7b-251677d5b07a.png)
If I were to hazard a guess, this is unintentional, and I was told to ticket it, so here we are.

**Comment by HackuJacku** [comment]
I've confirmed that this is now fixed, thank you for reporting it :)
