### ISSUE TITLE
Votecrate dispenses wrong quantity of items

### ISSUE THREAD

**Issue by Deathnight7976** [NebulaMC-GG/Support#1328]
Upon receiving a "5x Exp. Candy L" I received 1x Exp. Candy L 
![CtGhzUp](https://user-images.githubusercontent.com/17133410/172075830-638299c5-3719-4def-bd5d-20e338e0ea98.png)
![Kg4FII0](https://user-images.githubusercontent.com/17133410/172075826-c93c7a37-a75c-43bb-b3e2-0874bb99d12e.png)
IGN: Deathnight7976
Server: Orion

**Comment by HackuJacku** [comment]
Fixed from next reboot, it's suppose to say 1.
