### ISSUE TITLE
My toxel won't evolve

### ISSUE THREAD

**Issue by VirusDelta** [NebulaMC-GG/Support#1333]
have a 56 toxel and it won't evolv
![toxel](https://user-images.githubusercontent.com/106950474/172108316-f83df394-d113-433a-904b-8045b81cd288.PNG)
e

**Comment by fatyg5** [comment]
Need your username and the server you play on.

**Comment by VirusDelta** [comment]
VirusDelta on the nebula orion

**Comment by Khrisstias** [comment]
Seems this a pixelmon bug, occuring due to toxel not having its evolution section in the species json.

**Comment by Menno165** [comment]
Closing the issue as it is solved, Toxel should be able to evolve again.

If the issue occurs again feel free to reopen the ticket.
