### ISSUE TITLE
Dusk Balls sell less than Premier Balls

### ISSUE THREAD

**Issue by Khrisstias** [NebulaMC-GG/Support#1334]
![2022-06-06_02 58 02](https://user-images.githubusercontent.com/37944220/172120128-32e0039e-1b5e-4f6a-94bf-c00916431c3f.png)

Dusk balls require platinum bases, while Premier require iron. Dusks are more expensive to craft and I think the prices should match that

**Comment by fatyg5** [comment]
Passed to Cen.

**Comment by Rasgnarok** [comment]
Closing, it's been fixed.
