### ISSUE TITLE
Voting issue

### ISSUE THREAD

**Issue by Kreestian02** [NebulaMC-GG/Support#1336]
IGN: Kreestian02
I tried voting this morning and while the websites accepted the vote, I didn't get any rewards in-game. The same thing also happened yesterday. Was told to put it here by a mod.

Thanks in advance

**Comment by fatyg5** [comment]
Voting should be fixed. One server may have issues, but the rest should be okay. I can refund a day's worth of vote rewards, I just need the server you play on.

**Comment by Kreestian02** [comment]
Okay thanks. I play on Orion.

**Comment by fatyg5** [comment]
I have put these in your inventory.
