### ISSUE TITLE
a totally not-huge power huge power azumarill (and a prinplup with utterly no power XD )

### ISSUE THREAD

**Issue by Toby-Wilson** [NebulaMC-GG/Support#1337]
![2022-06-06_18 45 51](https://user-images.githubusercontent.com/14019602/172137925-e8becdda-5228-4883-99ec-900675e7ada9.png)
![2022-06-06_18 53 35](https://user-images.githubusercontent.com/14019602/172137936-19df7d87-6b2b-476d-af7f-ad7cdbee8eba.png)

so this i think happened by having both pokemon holding xpshare items (not the xp-all) i dunno when the change occured but they did have the items when they evolved, i'm not sure if they had pokerus at the time or not

as far as i can tell that is thier stat too, but have only been able to try hit things at lv 50 or so (azumaril's just under 40 there iirc)

**Comment by Rasgnarok** [comment]
This should now be fixed, it was a Pixelmon bug. Closing!
