### ISSUE TITLE
Vote Crate Prize Issue

### ISSUE THREAD

**Issue by TitanOfLore** [NebulaMC-GG/Support#1339]
I pulled a non-existent item (a Galarica Wreath) from the vote crate and it gave me nothing. It also seems to be missing from the vote crate preview menu, along with a few other items. Also, a much smaller issue, there is a typo on the Heavy Duty Boots that show them as just [x Heavy Duty Boots] on the vote crate preview menu.

**Comment by HackuJacku** [comment]
Both are now fixed :) If you speak to an Admin, they'll refund the Galarica Wreath!
