### ISSUE TITLE
Pokerus glitch

### ISSUE THREAD

**Issue by Danurrito** [NebulaMC-GG/Support#1340]
Hello,
Pokerus glitch caused the Hp, speed, attack of my wailmer to jump and has put it in a state of perma-faint. Trying to use a healing machine does nothing, if it revives on its own it will only have 1 hp and will faint upon attempt of healing.

![unknown (6)](https://user-images.githubusercontent.com/43429496/172153039-f7f3e34e-cb77-4e4c-9761-29766b62cdaf.png)

**Comment by fatyg5** [comment]
Pokerus has been disabled per next restart pending a fix
