### ISSUE TITLE
Kantonian Graveler dropping cobblestone instead of tumblestones.

### ISSUE THREAD

**Issue by Shika-The-Deer** [NebulaMC-GG/Support#1344]
Kanto-Graveler has Bauxite Ore, Gravel, and Tumblestones listed as possible drops in a fresh pokedrops.json file, but while hunting them down on the server it instead dropped cobblestone in place of the tumblestone in the rare item slot

(Drops I got while on the server, blank slot is Bauxite Ore that I had already claimed from the drops)
![image](https://user-images.githubusercontent.com/34965947/172226085-81403afc-8656-4f48-95db-31b797704e2c.png)
(Drops I got while in singleplayer)
![image](https://user-images.githubusercontent.com/34965947/172226559-b9cd17ba-dd63-4d00-9c3d-598fef7f23fa.png)

**Comment by fatyg5** [comment]
Weird, let me look into this

**Comment by fatyg5** [comment]
Passed to Cen since he's the eco guy. Hopefully we can get it added to the drops file

**Comment by CenizaRey** [comment]
Fixed, closing
