### ISSUE TITLE
Box deleting items

### ISSUE THREAD

**Issue by EpicBrandonAndBlizzard** [NebulaMC-GG/Support#1348]
As the title states, I had some items in a box and I broke the box. It deleted the items, lost some apicorns and I wanna say more items earlier that I didn't realize. [Maybe a vote key and some other items but I don't remember]

**Comment by EpicBrandonAndBlizzard** [comment]
epic_brandon
server: Orion

**Comment by fatyg5** [comment]
Refunded. Boxes will need to be used with caution
