### ISSUE TITLE
Buying Astral Key dupes it

### ISSUE THREAD

**Issue by CaptainTCovenant** [NebulaMC-GG/Support#1352]
I purchased x1 Astral Key, obtained it in game, but maybe 10 seconds later it gave me another. Since then its been repeatedly giving me an astral crate key. 
![Screenshot_105](https://user-images.githubusercontent.com/92965754/172272196-58b0173f-55ce-4823-b8a3-2d1b3b0288f8.png)
![Screenshot_106](https://user-images.githubusercontent.com/92965754/172272198-009ef24e-8ba8-41f1-9aaa-0d4b1295db25.png)

**Comment by CaptainTCovenant** [comment]
note: seems to be giving everyone them.

**Comment by fatyg5** [comment]
This was fixed. Thank you for the report!
