### ISSUE TITLE
Crate distributes wrong amount of money

### ISSUE THREAD

**Issue by Jayparalysis** [NebulaMC-GG/Support#1353]
Wrong amount of money was awarded from one of the 3 crates. I won 75k but was awarded 750k 
![Screenshot_1](https://user-images.githubusercontent.com/107003183/172272633-0b4ea969-170d-4c12-8316-1cae168dd288.png)

**Comment by HackuJacku** [comment]
Hi @Jayparalysis, which crates were these please? Also, which server was this? I'm also going to correct your balance if that is okay?

**Comment by Jayparalysis** [comment]
I believe I got that from an astral crate on Orion. Do whatever you need to correct the situation! Thanks for the assistance.

**Comment by MissElyri** [comment]
Fixed.
