### ISSUE TITLE
Gold hourglasses not producing egg

### ISSUE THREAD

**Issue by dshannon519** [NebulaMC-GG/Support#1355]
Put 2 gold hourglasses on ranch on an already progressed cycle, no egg, waited 10 min more, nothing. 
Reset ranch then used full 5 gold hourglasses which also didn't produce an egg

**Comment by dshannon519** [comment]
To update based on info seen in support on discord, seems that holding hourglasses as a stack consumes the entire stack and only adds 1 stage to the ranch

**Comment by Khrisstias** [comment]
The hourglasses using up the entire stack is a reported pixelmon bug. As for your pokemon not giving you an egg...can you describe to me in full detail your setup and what pokemon you're breeding? So i can test if it's a pixelmon or nebula issue.
