### ISSUE TITLE
Redstone Lamp (Breeding)

### ISSUE THREAD

**Issue by zTsuno** [NebulaMC-GG/Support#1358]
Redstone lamps are only showing lit as if they were unlit, so instead of 3 on breeding, they get one point per lit lamp

**Comment by fatyg5** [comment]
Can you confirm this in SP? If so, can you report it to Pixelmon?

**Comment by Menno165** [comment]
Closing the ticket since Pixelmon is reworking their breeding mechanics.
https://pixelmonmod.com/tracker.php?p=2&t=18082
