### ISSUE TITLE
Gold lures (strong) decaying into silver frames when they expire

### ISSUE THREAD

**Issue by Toby-Wilson** [NebulaMC-GG/Support#1359]
when a gold lure expires a silver frame is being returned (tried twice at time of writing) not sure if this is intended design but will mention it here

**Comment by Khrisstias** [comment]
Can confirm this also happens in singleplayer. Seems this is not reported on the pixelmon bug tracker so could you pretty please make a ticket here: https://pixelmonmod.com/tracker.php?p=2 be as descriptive as possible!

**Comment by Toby-Wilson** [comment]
have done - ok to close this issue over here then? or should i keep it open?
