### ISSUE TITLE
Vote crate being stuck in an opening state

### ISSUE THREAD

**Issue by redjeff1** [NebulaMC-GG/Support#1360]
the crate is stuck being opened as it has not given me anything or stopped opening and I can't seem to find any way to stop it. it seems to persist even though I log out and back on.
![Capture](https://user-images.githubusercontent.com/48700761/172522215-2dc22c74-8200-4ca1-ad35-105cb5ac56f3.PNG)

**Comment by ZeebLUL** [comment]
I have the same thing and it never gave me the Dragon Scale that showed up when I opened the crate. mc username: ZeebLUL
![VoteCrate](https://user-images.githubusercontent.com/107092760/172530070-a1bff941-434e-41cb-94dd-9766ce99391b.jpg)

**Comment by HackuJacku** [comment]
Hey @redjeff1! This should now be fixed, can you confirm it for me please? :)
