### ISSUE TITLE
$200K Reward for Cosmic Crate not working

### ISSUE THREAD

**Issue by QuinnActually** [NebulaMC-GG/Support#1362]
I'm gonna preface this by being totally honest here and saying that I didn't actually buy this Cosmic Crate key, but that being said, better me than someone who spent money to find this out, right? Anyway, as evidenced here, the $200K reward doesn't correctly reward money.
![image](https://user-images.githubusercontent.com/55411824/172527854-76345246-a496-4104-8706-14e830e2257f.png)

**Comment by QuinnActually** [comment]
![image](https://user-images.githubusercontent.com/55411824/172527965-63802a98-62ba-4234-adc6-f6e62ad7aca2.png)
Whoops, forgot to attach the second image. Silly me!

**Comment by fatyg5** [comment]
Refunded.
