### ISSUE TITLE
Trade holder recipe broken

### ISSUE THREAD

**Issue by darknegadude** [NebulaMC-GG/Support#1365]
The recipes for both sides of a trade machine give the left sid
![2022-06-08_01 42 46](https://user-images.githubusercontent.com/49503839/172560617-98b5d0e6-8104-41f7-97e1-97177377100d.png)
![2022-06-08_01 29 30](https://user-images.githubusercontent.com/49503839/172559822-23affbe1-b801-4152-ae47-3e4a9eee3875.png)
oddly enough, the opposite is true on my singleplayer test world
![2022-06-08_01 30 25](https://user-images.githubusercontent.com/49503839/172560036-f2094cf8-328a-484d-9340-7e9945261656.png)
![2022-06-08_01 30 29](https://user-images.githubusercontent.com/49503839/172560049-de011fc5-654a-4436-9d74-de4eb0ba5fbd.png)
JEI displays the correct recipes on both singleplayer and server

**Comment by Khrisstias** [comment]
This a reported bug on the pixelmon tracker. Thanks for your ticket!

**Comment by fatyg5** [comment]
Funny issue, I don't know why this is broken. Both files for the recipe are correct in the mod.

Anyway, Pixelmon issue already reported, as stated. Closing. Thanks for the report!
