### ISSUE TITLE
move relearner

### ISSUE THREAD

**Issue by Zylo808** [NebulaMC-GG/Support#1366]
move relearner doesnt work

**Comment by CenizaRey** [comment]
Can you be a little more specific? What about him doesn't work? Can you enter his GUI? What do you see when you do enter his GUI? Can you click any buttons? Is he displaying the correct moves for the pokemon? This is all important information we need if you want this to get fixed quickly

**Comment by Khrisstias** [comment]
Move relearner is bugged, it's a pixelmon bug and is on their tracker. Thanks for your ticket anyways.
