### ISSUE TITLE
Megastone crate key "lost"

### ISSUE THREAD

**Issue by williamrunes** [NebulaMC-GG/Support#1368]
I just won a megastone create key, but when I go into the megastone create it says that I don't have any
![image](https://user-images.githubusercontent.com/107142352/172683610-51aa05a9-9139-406b-b36f-195ffd6adfb8.png)
![image](https://user-images.githubusercontent.com/107142352/172683683-50799a46-8a90-4fec-90f8-bc4a132583da.png)

**Comment by fatyg5** [comment]
Username and server please?

**Comment by fatyg5** [comment]
I have readded this to your inventory on Atlas.
