### ISSUE TITLE
mah vote! it was eaten! by a hungry crate! XD

### ISSUE THREAD

**Issue by Toby-Wilson** [NebulaMC-GG/Support#1372]
![2022-06-09_08 15 09](https://user-images.githubusercontent.com/14019602/172730164-16ec12ff-37d8-4679-960d-8be33e99cc83.png)
![2022-06-09_08 15 30](https://user-images.githubusercontent.com/14019602/172730166-22c893d5-1a6b-4542-b1d3-1c1162085101.png)

didn't get the growth modifier - tried to show both inventory and chat screen

**Comment by fatyg5** [comment]
Need your username and the server you're on

**Comment by Toby-Wilson** [comment]
Wedgetail38 on Atlas

**Comment by fatyg5** [comment]
I have placed one in your inventory.
