### ISSUE TITLE
Rank Permission Issue

### ISSUE THREAD

**Issue by CaptainTCovenant** [NebulaMC-GG/Support#1373]
Recently bought the Omen rank on Orion, after waiting a while I tried to use various commands the rank gives you, none of which I had permissions for (aside those from staff).

all of the /kit's do not work, 
none of the other commands work such as /pc, /pokeheal, /me, /hat, /launch, /fly etc. 

Did however get the money and claim blocks. None of the keys (at moment of this, unsure if the keys are up yet for those crates, but worth noting).

Server: Orion
Username: CptTCovenant
Rank: Omen

**Comment by fatyg5** [comment]
Fixed.
