### ISSUE TITLE
Wrong amount given to players in Cosmic Crate

### ISSUE THREAD

**Issue by CaptainTCovenant** [NebulaMC-GG/Support#1375]
I won 75,000 from a Cosmic Crate, but it rewarded 750,000
![Screenshot_109](https://user-images.githubusercontent.com/92965754/172741571-92c56fb3-8ba2-45e2-8598-ad9ab8831f14.png)

Server: Orion
User: CptTCovenant

**Comment by fatyg5** [comment]
Fixed.

**Comment by CaptainTCovenant** [comment]
![Screenshot_110](https://user-images.githubusercontent.com/92965754/172745143-eaf7cd57-ab9d-4892-aba7-962a362ed8e3.png)
still borked. 
150k and 100k have rewarded nothing as well.
![Screenshot_111](https://user-images.githubusercontent.com/92965754/172745257-43c81f49-8828-4569-a410-3cee248fad7f.png)

**Comment by CaptainTCovenant** [comment]
Astral crate on Orion, gave 500k instead of 50k
![Screenshot_112](https://user-images.githubusercontent.com/92965754/173170919-843f60fc-7ee8-460c-8dd0-233a59420b1a.png)
