### ISSUE TITLE
[Ban Appeal] [ItsTachanks] Why I should be unbanned and what I'll do

### ISSUE THREAD

**Issue by Its-Tachanks** [NebulaMC-GG/Support#1376]
Over 1 year ago, I was banned for abusing a money duplication glitch that allowed me to purchase an entire shop's worth of items. I understand how hard it is to convey emotions and genuine feelings over text, but rest assured that I understand what I did wrong. Not only was the glitch I using benefiting myself solely, but more importantly, it harmed others by buying out other peoples' shops and causing issues with them. If it were not harming others it still would've been wrong, but since this glitch also affected shop owners, it was something I should've realized as I found/used the duplication glitch. I really enjoyed my time playing on this server, putting many hours into the game. Like I said, stuff like this is hard to show true honesty and because of that I want to re-emphasize the fact that I won't abuse any glitches from here on out. If I find something like this again, I'll report it to this issues forum rather than abusing it. Overall, I'm hoping you will consider this appeal to be genuine in hopes I can play on this server again, thanks. 

Btw, my IG name is 'ItsTachanks' as said in the title. My Microsoft name is also 'LordTachanks' if that matters at all

**Comment by MissElyri** [comment]
You should be able to log in now. I've tried to friend you and reach out to you on discord, but you haven't responded. If you're still unable to log into the server, please feel free to DM me there!
