### ISSUE TITLE
Not reciving modifiers

### ISSUE THREAD

**Issue by Jayparalysis** [NebulaMC-GG/Support#1377]
I won a growth modifier but did not receive it. Same happened with a cosmetic modifier but I have no proof of that. 

![Screenshot_1](https://user-images.githubusercontent.com/107003183/172765326-bf83fa3d-bcb3-4f86-a33e-b38a9c45b53c.png)

**Comment by HackuJacku** [comment]
Hi @Jayparalysis! How did you run the Growth Modifier exactly please? e.g: Which crate is this from please?

**Comment by Jayparalysis** [comment]
> Hi @Jayparalysis! How did you run the Growth Modifier exactly please? e.g: Which crate is this from please?
My bad! I got it from the vote crate
