### ISSUE TITLE
Stuck vote crate

### ISSUE THREAD

**Issue by Blaius** [NebulaMC-GG/Support#1382]
I voted 4 times in total and went to go use my keys. The first key I got a power band and when I used the 2nd key someone used the vote crate at the same time. I didn't get my item and my key is gone, and I'm not able to open vote crates again. It just says I'm already opening a crate.
![image_2022-06-09_124246895](https://user-images.githubusercontent.com/107210251/172910540-a090d208-d945-4a19-97f1-f0ff360fa1d0.png)
![unknown](https://user-images.githubusercontent.com/107210251/172910625-b3de83f9-1d83-40c4-bd44-5089ff6834de.png)

**Comment by MissElyri** [comment]
I can refund your keys, I just need to know what server you're on

**Comment by Blaius** [comment]
I'm on Titan, sorry for not saying

**Comment by HackuJacku** [comment]
Hi @Blaius! Were you refunded in the end?

**Comment by Blaius** [comment]
I never got a refund

**Comment by MissElyri** [comment]
Did I not redund you?

**Comment by Blaius** [comment]
no, i didn't get refunded that i know of

**Comment by MissElyri** [comment]
I'm almost certain I refunded this but didn't close the tracker. It's fine tho. I'll be home soon and I'll reissue these

**Comment by Blaius** [comment]
if you did refund already its ok, you dont have to

**Comment by Rasgnarok** [comment]
Was this refunded, @MissElyri ?

**Comment by MissElyri** [comment]
Refunded
