### ISSUE TITLE
Astral Crate Overpay

### ISSUE THREAD

**Issue by Jayparalysis** [NebulaMC-GG/Support#1385]
Bought some Astral crate keys and won 50k but was awarded 500
![Screenshot_1](https://user-images.githubusercontent.com/107003183/172953815-9ef4d778-07b0-4277-b048-d346149e6e95.png)
k

This was on Orion!

**Comment by ElementalMP** [comment]
Hey Jay, is this still an issue? 

Cheers!

**Comment by MissElyri** [comment]
@ElementalMP The money has been removed however I don't know if the underlying issue is still there.

**Comment by Rasgnarok** [comment]
Fixed
