### ISSUE TITLE
My inventory imploded or smth ;c

### ISSUE THREAD

**Issue by LuigiFrontiers** [NebulaMC-GG/Support#1387]
I didn't initially delete Serene Season and some weird stuff happened to my game. Even after deleting it my inventory is still messed up in some area: I have a Shaymin form changing item that I shouldn't have, I have a Macho Brace that I shouldn't have, and I can only wear pants on my head.

https://user-images.githubusercontent.com/107091311/172985468-060516e0-259a-4974-b926-1011961360cb.mp4

**Comment by ElementalMP** [comment]
Huh, that's weird. We'll need some more details on this one- are you able to upload here your debug log, and the list of mods your have installed to your client?

Cheers

**Comment by LuigiFrontiers** [comment]
Here. 
![image](https://user-images.githubusercontent.com/107091311/172986459-07a121a3-d163-41e7-be31-8a119f6ae80a.png)
idk how to get debug logs

**Comment by ElementalMP** [comment]
No worries, you can find your logs [here](https://github.com/NebulaMC-GG/Support#finding-your-logs). 

Are all your items mixed up, or just the ones in your inventory?

**Comment by LuigiFrontiers** [comment]
Only inventory items. I've found that my pants issue in particular is most likely client side as well because my friends did not notice anything odd. I have 5 debug logs for some reason... I hope they help y'all out.

[debug-1.log.gz](https://github.com/NebulaMC-GG/Support/files/8875698/debug-1.log.gz)
[debug-2.log.gz](https://github.com/NebulaMC-GG/Support/files/8875700/debug-2.log.gz)
[debug-3.log.gz](https://github.com/NebulaMC-GG/Support/files/8875701/debug-3.log.gz)
[debug-4.log.gz](https://github.com/NebulaMC-GG/Support/files/8875702/debug-4.log.gz)
[debug-5.log.gz](https://github.com/NebulaMC-GG/Support/files/8875703/debug-5.log.gz)

**Comment by ElementalMP** [comment]
Looks like you need to update your pixelmon client. Update pixelmon, and update us here and let me know how you get on!

**Comment by LuigiFrontiers** [comment]
Good news, i did in fact update. Bad news, nothing changed ;c. I am using the Apex Pixelmon Reforged modpack

**Comment by fatyg5** [comment]
Closing
