### ISSUE TITLE
Bold dont work for my /nick

### ISSUE THREAD

**Issue by KrogerMoney** [NebulaMC-GG/Support#1389]
My /nick wont let me bold it! i can color my name just not any of the other things you can do like underline or bold
![nick no work](https://user-images.githubusercontent.com/107235456/172991823-5bc1358d-450c-4ccd-886c-b6fd55ad85f5.png)

**Comment by RudolfShmitler** [comment]
Hey Kroger!

Gotta do the colour and then any bolding/italicizing/underlining, otherwise it won't pick up properly. Try &5&lKroger&2&lMoney instead, no need for the username after the nickname too.

**Comment by MissElyri** [comment]
@KrogerMoney I'm gonna assume the above mention has helped. Closing for now. If it persists reopen a ticket. :)
