### ISSUE TITLE
/pokenick doesn't work

### ISSUE THREAD

**Issue by ConversaBC** [NebulaMC-GG/Support#1394]
I have access to /pokenick via the Rune Rank, but the command doesn't work. I've tried various strings of codes for nicknames and nothing comes up in the chat. For example: I would type "/pokenick 1 {#AA0000}Raboot" or "/pokenick 1 &5Raboot". Literally nothing happens when I enter the first example, but the second one is different. The console tells me that I "don't have permission to use &5" when using /pokenick. However, on the website when buying the Rune Rank, it says you should have permission to use all Minecraft color codes with /pokenick.

**Comment by Rasgnarok** [comment]
Now works as intended, closing.
