### ISSUE TITLE
Transferring claim blocks to others doesn't work

### ISSUE THREAD

**Issue by sun6002** [NebulaMC-GG/Support#1396]
I've tested this with CptTCovenant, and while it seems he can transfer blocks to me, I can't transfer them back to him (or to anybody else).  An error shows when I try to input /transferblocks [playername] [amount]:
![Capture](https://user-images.githubusercontent.com/106930193/173165125-b94e84ba-3e66-486f-b735-c318a900a8cf.PNG)

It's worth noting that this error shows even when I have enough claim blocks to make the transfer (I was sending 1 at the time as a test when I got that screenshot).

**Comment by PrimalCyndaquil** [comment]
Closing as this is now fixed- had multiple players transfer a small amount of claim blocks and the command now works fine back and forth, even when a player is at the purchaseable claim block limit.
