### ISSUE TITLE
Cosmetic crate not opening despite having cosmetic keys

### ISSUE THREAD

**Issue by Khrisstias** [NebulaMC-GG/Support#1397]
![2022-06-10_23 54 51](https://user-images.githubusercontent.com/37944220/173173306-ecb29941-af8b-4dc2-809e-306a6676d804.png)

**Comment by RudolfShmitler** [comment]
Cosmetic crate not currently active, not sure when it'll go up but we'll be told I would assume

**Comment by MissElyri** [comment]
Rud is correct; They're still currently disabled. We will be sure to let everyone know when they're up and running!
