### ISSUE TITLE
Scroll of Waters/Darkness crashing players within rendering distance if broken 

### ISSUE THREAD

**Issue by Khrisstias** [NebulaMC-GG/Support#1402]
It can even crash people who didn't break it but only in rendering distance.

Latest: https://zerobin.net/?bc3a06e4d813c356#97hQTg5nP5k3UdbsniNx5Hg/ZU/JjVnXtLVIMIuuWiw=

Debug: https://zerobin.net/?58684d6eb497ff2c#MNbcj8UW2i/jYRmj22mYPWPgcQynmvPOcvvu08c1hLc=

**Comment by Rasgnarok** [comment]
This was forwarded internally to Pixelmon, thank you!
