### ISSUE TITLE
Not correct names/icons/items

### ISSUE THREAD

**Issue by EpicBrandonAndBlizzard** [NebulaMC-GG/Support#1404]
In the vote crate, several items aren't labeled right and thus give different rewards. Such as the items in the picture [Which were much better in my opinion actually lol]. On a side note, I also lost a vote key when the server went down just as I was opening the crate. 
![image_2022-06-11_203545473](https://user-images.githubusercontent.com/106925279/173209422-8e1dbd34-f401-40ef-80df-1d0d7ee63081.png)

**Comment by Rasgnarok** [comment]
Just to confirm, you are running Pixelmon 9.0.2 yes? There's currently a mismatch of block/item IDs if you login with either Serene Seasons, or Pixelmon 9.0.1.

**Comment by Rasgnarok** [comment]
Closing, OP inactive.
