### ISSUE TITLE
/tpa and /tpahere not appearing for receiving player

### ISSUE THREAD

**Issue by RudolfShmitler** [NebulaMC-GG/Support#1405]
When I send a /tpa or /tpahere to anyone on the server, they don't receive anything. When I try to send another one it says there's already an outstanding request. Have tested on Atlas and Orion, haven't tried Titan.

**Comment by Menno165** [comment]
Closing the issue as the messages can be seen and are working on all 3 servers.
If the issue re-occurs feel free to re-open the issue.
