### ISSUE TITLE
Pokemon drop glitch

### ISSUE THREAD

**Issue by Jayparalysis** [NebulaMC-GG/Support#1406]
Upon defeating a Pokemon and pressing the ESC key, no items will be dropped. However if you defeat a Pokemon after and decide to pick up those drops, you'll get the previous drops instead.
![Example_1](https://user-images.githubusercontent.com/107003183/173216731-841a528b-0818-4869-b341-5282c8d97ab5.png)
Here I defeat a Snover and press ESC because I do not want the drops to clutter the world.
![Example_2](https://user-images.githubusercontent.com/107003183/173216814-d092b66c-b637-4e68-b844-9bd3204e672e.png)
Then I immediately faint a Swinub and when I attempt to take the drops I get the following items
![Example_3](https://user-images.githubusercontent.com/107003183/173216852-1f98115e-bb35-4993-9aa3-bb7e13f1de69.png)
2 Snowballs and 1 leather

**Comment by Rasgnarok** [comment]
This should be forward to the Pixelmon tracker, it's a really odd, and definitely mod-related bug: https://pixelmonmod.com/tracker.php?p=2

**Comment by Jayparalysis** [comment]
I've sent in a ticket for this issue! Thanks for your assistance!

**Comment by Khrisstias** [comment]
This was fixed as of 9.0.5. Closing
