### ISSUE TITLE
Den Error

### ISSUE THREAD

**Issue by ShapooK** [NebulaMC-GG/Support#1407]
Was about to do a HA gible den, as soon as i gmaxed and choose to attack the gible, i got this error and it made the den finish and act like if i failed it. Happened between 12:52-12:56 am, Sunday June 12/2022 Titan server
![download](https://user-images.githubusercontent.com/35164973/173220772-08807b31-569f-407a-a5b1-c327274979ab.png)

**Comment by MissElyri** [comment]
Do you have proof of it being HA by chance? I can refund the den but I can't promse it'd be HA :(

**Comment by ShapooK** [comment]
Sadly no, since i click fast i just tried to grab that error as fast as i could!

**Comment by Rasgnarok** [comment]
Closing, this should now be fixed.
