### ISSUE TITLE
Astral Crate Rewards Issue

### ISSUE THREAD

**Issue by TobyJB** [NebulaMC-GG/Support#1412]
I purchased an astral crate key and then used it to open an astral crate, i recieved 3 random shiny pokemon, immediately after i recieved them, the server i was on (atlas) crashed and i was returned to the hub, when i relogged into atlas, my 3  random shiny pokemon reward was gone, could i please be reimbursed the astral crate key, 3 random shiny pokemon, or the full amount that i paid for the astral key? thank you <3

**Comment by MissElyri** [comment]
What is your username on Atlas? I can refund you whenever you're next online.

**Comment by TobyJB** [comment]
I am online right now if You are able to refund now?

**Comment by MissElyri** [comment]
I just got home from work, if you're still around lmk. I'll be up for a while
