### ISSUE TITLE
Battle glitch

### ISSUE THREAD

**Issue by CaptainTCovenant** [NebulaMC-GG/Support#1413]
Given there is the current one-message chats when in battle, some people get hit with a waiting glitch and cannot /endbattle if they have chatted just before. 

Currently Moderators (from my experience) can't /endbattle (user) - would be very helpful to enable this for Mods. 

Server noticed on: Orion

**Comment by Rasgnarok** [comment]
Added to moderators, let me know if everything works as intended!
