### ISSUE TITLE
Modifier not showing Color Codes in messages

### ISSUE THREAD

**Issue by zTsuno** [NebulaMC-GG/Support#1416]
When you use a level down modifier it shows a gigantic message for unidentified color codes.
I am unsure if it is like so for the other modifiers.

![2022-06-13_10 29 40](https://user-images.githubusercontent.com/106882836/173384756-ab61fcf1-b8b1-4550-a6dc-33b9691fa4d1.png)

**Comment by Rasgnarok** [comment]
This should now be fixed as of today, closing.
