### ISSUE TITLE
Modifier not given when I used the crate

### ISSUE THREAD

**Issue by zTsuno** [NebulaMC-GG/Support#1417]
I used a astral and a solar crate key and got 3 modifiers a couple days ago and was not given neither my level down -5 modifier nor my 2 form modifiers.
IGN: StepSisTsunade
Server: Orion
Also here the picture for the 2 form modifiers and the level down is at the top of the chat.
![2022-06-10_00 47 10](https://user-images.githubusercontent.com/106882836/173382940-bea0a324-5a66-4468-9ec8-f9854aaaa5b8.png)

**Comment by Rasgnarok** [comment]
Just need this refunded, as the ModifierToken themselves were simply offline at the time this happened.

**Comment by Rasgnarok** [comment]
When will you be online so that me or Elemental can refund it, @zTsuno ?

**Comment by Rasgnarok** [comment]
Closing, OP inactive.
