### ISSUE TITLE
Legacy Rank Coupon - Mega Ticket

### ISSUE THREAD

**Issue by fatyg5** [NebulaMC-GG/Support#1418]
Please fill out the following format to receive your Legacy Rank Coupon:

Username:
Discord Username:
Server Redeemed On:

Example Reply
Username: Fatyg5
Discord Username: Fatyg5#0001
Server Redeemed On: Atlas

You must fill out your Discord Username with the numbers or your coupon will not be rewarded! Please give time for us to send you your coupon!

**Comment by lexjo** [comment]
lexjo
lexjo#9586
Orion

**Comment by lolsikinz** [comment]
lolsikinz
Sweed#4664
Titan

**Comment by MasonWindu1029** [comment]
Mason_Windu
Mason_Windu#0586
Atlas

**Comment by EnderLord360** [comment]
IceEnderKevin
EnderSteve#3878
Atlas

**Comment by Khrisstias** [comment]
Username: DraconiacLatias
Discord Username: NonbinaryDragon#1871
Server Redeemed On: Orion

**Comment by xTwilly** [comment]
xTwilly
Twilly#2299
Atlas

**Comment by Tairano420** [comment]
Tairano_
Tai#5626
Atlas

**Comment by redx10** [comment]
Username:Valirus
Discord username: vali is invalid #4334
Server redeemed on: Orion

**Comment by Lacourteous** [comment]
Green213
Laco#6670
Atlas

**Comment by Kirikoz** [comment]
Kirikoz
Kiri#6050
Atlas

**Comment by ProfAwesome100** [comment]
Profawesome100
Prof#9144
Atlas

**Comment by fatyg5** [comment]
Any future users, we will contact you via email, discord, or in-game for the coupon information! Sorry about the confusion!
