### ISSUE TITLE
only gave me 1x ball modifier when i should have gotten 3x

### ISSUE THREAD

**Issue by ytskylerplayz** [NebulaMC-GG/Support#1426]

**Comment by Rasgnarok** [comment]
Can I please have your username, as well as the server you play on?

**Comment by ytskylerplayz** [comment]
my user is yt_skylerplayz and i play on orion

**Comment by HackuJacku** [comment]
@ytskylerplayz - how did you get these modifiers so I can fix it for the future please?

**Comment by ytskylerplayz** [comment]
The crates

Sent from my T-Mobile 5G Device
Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________

**Comment by HackuJacku** [comment]
Which one please? Vote?

**Comment by ytskylerplayz** [comment]
i believe cosmic

**Comment by HackuJacku** [comment]
@ytskylerplayz - I have added an additional two Growth Modifiers to your inventory. Sorry for the delay - I've given you an additional one (3) as compensation.
