### ISSUE TITLE
/Breed and /hatch don't work

### ISSUE THREAD

**Issue by CaptainTCovenant** [NebulaMC-GG/Support#1427]
/breed come up as 'unknown command' when trying to use it with the Omen rank. 
/hatch fails to recognize player name + party slot, at least from what I can see.
![Screenshot_117](https://user-images.githubusercontent.com/92965754/173483856-80020873-4afa-4c04-9d85-2bdce92a4dd3.png)

Server: Orion

**Comment by HackuJacku** [comment]
This bug is now fixed, thank you for the report :)
