### ISSUE TITLE
White Stripe Basculin won't evolve after I made it take 450 recoil in one life.

### ISSUE THREAD

**Issue by zTsuno** [NebulaMC-GG/Support#1429]
IGN: StepSisTsunade
Server: Orion

Ive been trying to train this basculin's recoil for 45 mins, through trial and error and it fainting. and I finally made it stay alive long enough to go well over the evolve conditions. Was wondering if It could get force evo'd into basculegion.

**Comment by fatyg5** [comment]
If you can't replicate this in Singleplayer, we will look into the issue and fix it for you. If this happens in SP, please report it to Pixelmon and await a fix from them.

Reopen if you can't replicate in SP please.
