### ISSUE TITLE
/kits have shorter cooldowns than intended

### ISSUE THREAD

**Issue by Qaz1337** [NebulaMC-GG/Support#1430]
claimed my rune monthly and it says 7 days remaining, idk if omens 90 day one is also bugged but might aswell check that when you fix 30 day cooldown ones, could be somewhat op

**Comment by fatyg5** [comment]
This should be fixed... but it reverted my changes. Pushing to Hacko, or possibly needs editing during server downtime.

**Comment by HackuJacku** [comment]
Hi @Qaz1337! Is this still an issue please?

**Comment by Qaz1337** [comment]
My monthly says 16days so I guess its fixed now
