### ISSUE TITLE
Backpacks are duping

### ISSUE THREAD

**Issue by lolsikinz** [NebulaMC-GG/Support#1431]
I just won a yellow backpack from the cosmetics crate and I accidentally right clicked twice and I now have two backpacks
![image](https://user-images.githubusercontent.com/9399603/173531371-04d74e41-b72f-4d0d-b95a-3b07a11b19a5.png)
It will duplicate based on the stack count of the backpack
![image](https://user-images.githubusercontent.com/9399603/173531717-343c9045-baeb-4a65-afd0-448f2b200af0.png)

**Comment by lolsikinz** [comment]
Titan and my username is lolsikinz

**Comment by fatyg5** [comment]
Gonna close, as assuming fixed per Hacko.
