### ISSUE TITLE
Server crash after crate opening

### ISSUE THREAD

**Issue by Kindersoldaat** [NebulaMC-GG/Support#1433]
![image](https://user-images.githubusercontent.com/107473854/173555994-e114700a-98e0-42e8-b156-dc011518e78b.png)
![image](https://user-images.githubusercontent.com/107473854/173556066-f06109f7-7847-4481-9fa7-8fdc370a2f57.png)

I cant seem to upload the vid so i took two screenshots of it. But the server crashes after you get 3 shiny pokemon from the asteral crate. I still do not have the pokemon after the server went up again.

**Comment by Kindersoldaat** [comment]
The_ace_trainer had the same problem aswell, hes the one who recorded it.

**Comment by LionelVorky33** [comment]
https://user-images.githubusercontent.com/14273898/173561756-104196ad-d6cd-4f8f-b87c-a81e12c98fe9.mp4


https://user-images.githubusercontent.com/14273898/173561770-f3ab9c10-9411-49ef-8c67-5870e6958b00.mp4

**Comment by HackuJacku** [comment]
This is now fixed, thank you for the report :)

**Comment by Kindersoldaat** [comment]
Kindersoldaat's shinies have been refunded, The_Ace_trainer still has to get his shinies, he'll contact someone about that!
