### ISSUE TITLE
Hiddan Ability mon from crate does not have HA

### ISSUE THREAD

**Issue by Jayparalysis** [NebulaMC-GG/Support#1436]
Won a HA Pineco from cosmic crate and it does not have its H
![Screenshot_1](https://user-images.githubusercontent.com/107003183/173660311-6e025b25-4e99-44d0-ac1e-4f4804a3927b.png)
![Screenshot_2](https://user-images.githubusercontent.com/107003183/173660318-59ee5062-a740-4ff7-ad33-de75af2bb665.png)
A

**Comment by ElementalMP** [comment]
Any admin should be able to fix this for you, let one know next time you're online!

**Comment by HackuJacku** [comment]
Forwarded this bug report to the PixelmonTeam. Thank you for reporting!
