### ISSUE TITLE
Unclaiming land.

### ISSUE THREAD

**Issue by SAZZILLY** [NebulaMC-GG/Support#1439]
hi, i would like to find a way to unclaim land i have done incorrectly (due to not know the workings behind it); i would like to wipe all the claims i have made. 

I'm on pixelmon titan area.

**Comment by ElementalMP** [comment]
Hey! Have you tried doing /abandonallclaims?

**Comment by SAZZILLY** [comment]
thank you for your help ! now i can claim properly :) have a good day !
