### ISSUE TITLE
Slowpoke tail can't be sold to shopkeepers

### ISSUE THREAD

**Issue by Augie279** [NebulaMC-GG/Support#1440]
Warping to /market and talking to one of the shopkeepers, the Slowpoke tails do not show up when trying to sell items. Despite this, holding shift and hovering over them says that they can be sold. Titan server if that's useful, thanks!

**Comment by fatyg5** [comment]
This is not an issue, Pixelmon provides the shift info, not us. It is intended to be sold in Pixelmon vanilla

Suggest it be added to shops here: https://github.com/NebulaMC-GG/Suggestions/issues/55
