### ISSUE TITLE
Vote crates are acting a bit weird

### ISSUE THREAD

**Issue by lolsikinz** [NebulaMC-GG/Support#1441]
I was opening my four daily vote crates and the first crate I opened didn't give the reward that rolled nor did it prompt my chat as having won that said item. but the other 3 logged with no issue but I didn't get the last item.
My items were already refunded but I am making this as it is a potential issue that could happen to someone else
The items that I got were (in order): 16x Lure Balls, Heavy Duty Boots, Rocky Helmet, Dynamax Candy
![image](https://user-images.githubusercontent.com/9399603/173692202-5c22dec3-ccbf-4440-8752-83c42248f12d.png)

**Comment by HackuJacku** [comment]
After looking into this, I can now confirm these rewards except the dynamax candy are fixed. Thank you for the report :)
