### ISSUE TITLE
No gift card code

### ISSUE THREAD

**Issue by lolsikinz** [NebulaMC-GG/Support#1444]
I was surprised to learn that a lot of people have the legacy rank gift cards already so when checking my /mail on Titan (the server I redeemed legacy rank on) I had no mail to speak of

![image](https://user-images.githubusercontent.com/9399603/173778758-0c1b41e7-6906-416c-896e-4c1c3cb4f199.png)

I even double checked and I don't have it on any of the other servers

Orion:
![image](https://user-images.githubusercontent.com/9399603/173779053-706de922-9e24-4a6c-80d3-1c93559d6f8c.png)

Atlas:
![image](https://user-images.githubusercontent.com/9399603/173779187-654e536f-258a-4f2e-b29e-8b7ba8c0266a.png)

It was Eon rank if that matters

**Comment by HackuJacku** [comment]
All gift cards have been given out, you should have received it so please can you check again?

**Comment by HackuJacku** [comment]
Sorry for the delay @lolsikinz! After looking into this, we're up to date in terms of giving the gift cards out. I'm going to close this but if you didn't receive yours, please DM me on Discord - my username is @Hacko#0001
