### ISSUE TITLE
Did not receive vote crate keys for voting.

### ISSUE THREAD

**Issue by Izayoi-Aki** [NebulaMC-GG/Support#1446]
I voted for the server on all 5 of the sites before I logged on to the server but did not get my vote keys upon logging on the the server I mostly play on.? I mainly play on Atlas.

**Comment by Rasgnarok** [comment]
You'll need to re-test to see if this is working for you again, because on my end it's going through fine.

**Comment by HackuJacku** [comment]
Hi @Izayoi-Aki! Did you manage to re-test this to confirm it's working on your end please?

**Comment by Izayoi-Aki** [comment]
I can try to recreate it tomorrow/later today but I avoided testing it by making sure I am logged onto the server when I vote.

**Comment by Izayoi-Aki** [comment]
So, I voted for all 5 sites before getting on the server and while it says I *can* vote on the server, going to the websites shows me as having already voted.

**Comment by Rasgnarok** [comment]
It's just a sync issue on the vote site, they don't send update packets fast enough. Not something we can fix, closing.
