### ISSUE TITLE
My Hoopa didnt get Hyperspace Fury

### ISSUE THREAD

**Issue by BumbleWeeb** [NebulaMC-GG/Support#1448]
When I leveled up my Hoopa (unbound) to lvl 85 it didn't learn Hyperspace Fury like it said it would ok the wiki and instead learned Hyperspace Hole like it was in the confined form. I don't know what to do since the relearner is bugged.

**Comment by fatyg5** [comment]
Please confirm if this is the case in Singleplayer and report it to Pixelmon. You will have to wait for Pixelmon to fix move relearners to learn this move.
