### ISSUE TITLE
Mystic Legacy Rank

### ISSUE THREAD

**Issue by sioaleni** [NebulaMC-GG/Support#1451]
I used to play on Oblique and I had Mystic rank. I saw that there is a way to reclaim this rank on the new rebranded servers, but the only problem is that I'm not playing on the same account I used before. Recently I attempted to migrate my old account to a Microsoft account, but due to complications I ended up just making a new account completely. I still have the receipt from when I first purchased the Mystic rank on the old Oblique server, but I was wondering if it was possible for me to somehow get it on the new Titan server.

**Comment by MissElyri** [comment]
Yes. Look in announcement channel for the link to the nebula store , click Legacy, then the Mystic Rank and follow prompts.  All old ranks are being converted into the "Legacy" rank and should be converted within 72 hours

**Comment by sioaleni** [comment]
It says "There are required packages you do not own." Probably because the mc account linked isn't the same account I previously owned the rank on.

**Comment by fatyg5** [comment]
That would most likely be correct, how would you expect to claim a rank if you're not using the same account as the one that had it? If you can provide proof the previous account that had the rank was yours, we can refund the purchase. Contact Rasgnarok#6969 or Fatyg5#0001 on Discord with said proof.
