### ISSUE TITLE
Didnt receive megastone key for my rune monthly kit

### ISSUE THREAD

**Issue by xTwilly** [NebulaMC-GG/Support#1453]
IGN: xtwilly
Server: Atlas

**Comment by itanomaly** [comment]
Can confirm, this happened to me to another player in Titan as well. (ign itanomaly on titan)

**Comment by Rasgnarok** [comment]
Fixed the underlying issue, players need refunding when next online.

**Comment by MissElyri** [comment]
@xTwilly @itanomaly DM me when ya'll are online
