### ISSUE TITLE
Used wrong name when purchasing crate keys.

### ISSUE THREAD

**Issue by zTsuno** [NebulaMC-GG/Support#1455]
I used my old IGN: StepSisTsunade, Instead of IGN: JiraiyaUwU and bough 5x Cosmic crate keys.
Server: Orion

Image removed by Hacko as it contains personal information

**Comment by HackuJacku** [comment]
Hi @zTsuno! The next time you log onto Orion, you should receive these. If you don't after 15 minutes, please do let me know :)

**Comment by HackuJacku** [comment]
Just confirmed you've got these, enjoy! :)
