### ISSUE TITLE
Vote Crates Reward Error

### ISSUE THREAD

**Issue by Lieren-HuntGhosts** [NebulaMC-GG/Support#1456]
The last 16x Premier Balls I rolled in the Vote Crates didn't get cashed out. Will probably need a little testing.

**Comment by HackuJacku** [comment]
Hey Lieren, after testing this I've confirmed that these are being given correctly. Which server did you originally have this issue on please?

**Comment by Lieren-HuntGhosts** [comment]
Titan

**Comment by HackuJacku** [comment]
After looking into this in further detail, I am unable to reproduce. If it's still an issue, please open a new issue when it occurs. Thank you :)
