### ISSUE TITLE
Didn't receive Ball Modifier from Solar Crate

### ISSUE THREAD

**Issue by ihatewiggers** [NebulaMC-GG/Support#1461]
https://i.imgur.com/bVgjyWe.png

I rolled the item but it never went into my inventory.

Character: 1b2o3b
Server: Titan
Crate: Solar

Posting so mods know and also I can actually get my item, tyvm.

**Comment by ElementalMP** [comment]
Let us know when you're online so we can refund this!

**Comment by Rasgnarok** [comment]
Already refunded, thanks Ele
