### ISSUE TITLE
Ball modifier from vote chest

### ISSUE THREAD

**Issue by killdeath166** [NebulaMC-GG/Support#1464]
I put my first vote key in and it said I got a ball modifier but I didn't get the item

**Comment by KoreanNino** [comment]
Just a guess, since I think modifiers are still disabled you didn't get your item because of that reason.

**Comment by HackuJacku** [comment]
This is now fixed. If you can provide us your IGN and server please, @killdeath166, we can refund you :)

**Comment by killdeath166** [comment]
Killdeath166 server orion

**Comment by HackuJacku** [comment]
Hi @killdeath166! I've added a Ball Modifier to your inventory on Orion, enjoy using it :)
