### ISSUE TITLE
Crates looking like glass

### ISSUE THREAD

**Issue by Lieren-HuntGhosts** [NebulaMC-GG/Support#1466]
![0a7975febb4064d4e844e941df50244d](https://user-images.githubusercontent.com/58639155/174442362-9b2ae574-b033-47a8-805f-d9e39b0b01c5.png)

All crates look like this

**Comment by HackuJacku** [comment]
Not a bug, requires new version of resource pack being released later today. Clicking them still opens the crates interface :)
