### ISSUE TITLE
Fossil Command Not Working

### ISSUE THREAD

**Issue by zTsuno** [NebulaMC-GG/Support#1467]
Omen Rank's get the command /redeemfossil it seems as the description says, But the server says this command doesn't exist yet.
I would assume that it doesn't work because of the fossil machines. But, just a ticket for the future.

**Comment by MissElyri** [comment]
Yes. It's reliant on that, So I'm gonna close it for now, However whenever I'm next online I'd love to exchange fossils for their respective mons.
