### ISSUE TITLE
Instant crash when entering Atlas/Orion/Titan with Litematica-forge, works perfectly in the hub and singleplayer.

### ISSUE THREAD

**Issue by AkihideTsugane** [NebulaMC-GG/Support#1471]
[crash-2022-06-17_14.38.26-client.txt](https://github.com/NebulaMC-GG/Support/files/8935429/crash-2022-06-17_14.38.26-client.txt)

Hello, 

There is currently an issue between NebulaMC server specifically and Litematica-Forge (https://www.curseforge.com/minecraft/mc-mods/litematica-forge).
It is possible to load into the hub with the mod, however, when using any of the 3 server portals, the game instantly crashes resulting in the crash log I added to this ticket. 

It doesnt seem to be an issue with Pixelmon alone since I'm able to use Litematica perfectly fine in singleplayer with Pixelmon.
I tested with and without the following mods that could have conflicted with the exact same result: Phosphour, Optifine.

I'm reporting it because afaik Schematica was commonly used in the Pixelmon 8/1.12.2 server, so maybe if there's any easy fix for this, it might help builders and/or casual players that want to build something nice. 

The issue has been previously reported by myself in #support-a channel https://discord.com/channels/151095626916954113/184700717456556032/987842763628376094  and discussed in the staffers channel with another staffer that had the exact same issue.

Feel free to DM me directly on Discord if I can add anything to this, Junichi#3865.
Thanks!

**Comment by Rasgnarok** [comment]
This seems to be a bug directly with litematica, in interacting with Forge on multiplayer. Our Hub (at the time) did not run Pixelmon, and therefore wasn't relying on the same classes this crash report mentions. I'd forward it directly to the litematica dev if I were you, as sadly, this is not something we, or Pixelmon, can fix.
