### ISSUE TITLE
{Titan} Mass pokemon spawning

### ISSUE THREAD

**Issue by Menno165** [NebulaMC-GG/Support#1472]
I came online on Titan to help real quick with an battle issue, when I noticed that a lot of pokemon have spawned around 3 players fighting an groudon boss. It caused a bit of a laggy sitation in that area.

![image](https://user-images.githubusercontent.com/84038836/174481681-abdb7e2e-7ed2-4ea7-b1da-b94dfae7e000.png)

**Comment by Rasgnarok** [comment]
This should be fixed, rates have been edited.
