### ISSUE TITLE
Air Blocks

### ISSUE THREAD

**Issue by Zoru-chan** [NebulaMC-GG/Support#1474]
Hey not sure what all drops it, however while camping a legend I killed a dubwool and it dropped 2 Air Blocks. I didn't take them but wanted to make sure all was known that some mons may drop air blocks, dubwool being one of them.

**Comment by dshannon519** [comment]
Like to add diggersby to list, will keep an eye out for more

**Comment by CenizaRey** [comment]
Fixed, closing
