### ISSUE TITLE
Lost my crate key

### ISSUE THREAD

**Issue by uziigk** [NebulaMC-GG/Support#1479]
A couple of days ago I bought a Astral keycrate but I didn't get to use it until yesterday because I out of no where had a busy schedule. I came online yesterday trying to use it and I got confused why it wasn't working, and then the server crashed. After it got put online again I checked my inventory and my wallet and I didn't receive anything. I can't show you the purchase agreement because for some reason my bank (ING, It's a dutch bank) doesn't allow me to make screenshots of my purchases. I did have my friends online (3ripleJ and Vinceboy9) who can confirm I did buy the key crate at that moment and used it before the crash.

**Comment by uziigk** [comment]
By the way, my IGN is 8hrr

**Comment by Rasgnarok** [comment]
Refunded, thanks!
