### ISSUE TITLE
Vote Crate Did Not Give 32x Ultra Ball Reward

### ISSUE THREAD

**Issue by CSpringer1220** [NebulaMC-GG/Support#1480]
Title. 

The "previous winner" did not even list me, as if it never happened, but I do have eyewitnesses who saw me win the reward in question. I have since been refunded, but I'm posting this just so it's known.

**Comment by HackuJacku** [comment]
Hi @CSpringer1220! What server is this please?

**Comment by CSpringer1220** [comment]
This happened in Titan

**Comment by MissElyri** [comment]
@CSpringer1220 Has someone been online to refund you? If not, what is your username and I can handle this whenever you're available

**Comment by CSpringer1220** [comment]
@MissElyri As mentioned in the original post, I have already been refunded. The purpose of this ticket was more to bring awareness to the situation.

**Comment by MissElyri** [comment]
I missed that, my apologies.

**Comment by HackuJacku** [comment]
After looking into this, I have confirmed it is no longer an issue. Thank you for the report anyways :)
