### ISSUE TITLE
Typo in broadcast message

### ISSUE THREAD

**Issue by Izayoi-Aki** [NebulaMC-GG/Support#1481]
The broadcast message that mentions joining the Discord to participate in events has a typo. it says "participle" not "Participate"
![3d85d10e1772944a8c06070b223b35f6](https://user-images.githubusercontent.com/101058538/174496535-26188135-0586-49e9-aacc-d5e61c73841c.png)

**Comment by CenizaRey** [comment]
Fixed as of next reboot, thanks for your report!
