### ISSUE TITLE
Ultraspace Ability Issue

### ISSUE THREAD

**Issue by Konanimo** [NebulaMC-GG/Support#1482]
The external ability for certain Pokemon to summon the Ultraspace portal is still active. If people are still getting into the Ultraspace that's most likely how they are doing it. Since people being in the Ultraspace causes massive lag to the server it would be nice to see this ability disabled for the time being.

**Comment by HackuJacku** [comment]
We've implemented something to stop players from getting to Ultra Space whilst there are issues within Pixelmon. Thank you for the report however :)
