### ISSUE TITLE
Solar crate no rewards.

### ISSUE THREAD

**Issue by xmuia** [NebulaMC-GG/Support#1486]
ign: DiscordNitro
server: titan

Got solar crate key from vote party, opened and got growth modifiier, but it didnt went to my eq.
 
![image](https://user-images.githubusercontent.com/51237159/174659225-df41c309-a027-42a0-ae2c-ea1907ee2f7f.png)
![image](https://user-images.githubusercontent.com/51237159/174659327-81cc6630-7082-47fb-a652-4aedd7050dca.png)

**Comment by PrimalCyndaquil** [comment]
Adding that I won a Cosmetic Kit and did not receive anything either. This seems to be an issue with multiple people flooding the crate at once. I can refund you in game real quick.

**Comment by HackuJacku** [comment]
After looking into this in detail, I have confirmed these are working correctly. I believe this was an issue with modifiers were disabled. If this issue is still persistent, please open a new bug report :)
