### ISSUE TITLE
Grabbed the wrong Legacy Rank

### ISSUE THREAD

**Issue by LanceKehisato** [NebulaMC-GG/Support#1489]
As the title says I had grabbed the wrong legacy rank due to my own error. I had misread my email receipts and didn't realize that I had bought the rank upgrade from Azure to Enigma. By this, I mean I had grabbed the Legacy Azure, instead of Legacy Enigma. Because of this, I have not received my coupon code. Attached are copies of the emails that serve as proof of the rank and rank upgrade.
![Proof of rank upgrade](https://user-images.githubusercontent.com/33641243/174685691-20a48424-2b62-4c34-8e2d-1724f5ec3d8b.png)
![Proof of rank before upgrade](https://user-images.githubusercontent.com/33641243/174685733-8cd9bd9b-d246-40a7-b690-2d3e1ea92172.png)

**Comment by Rasgnarok** [comment]
I'll be sending the gift card through in-game mailing system shortly, with the correct amount, thanks!
