### ISSUE TITLE
Helper commands suggestions

### ISSUE THREAD

**Issue by Lieren-HuntGhosts** [NebulaMC-GG/Support#1492]
We helpers have access to /compsearch, but we don't have /pokesee, back in 2020 we did have it. I dont know why shouldn't wee, but feels like we should be able to see other people's teams if they request help for certain stuff, like " why isn't this pokemon of mine evolving :( "

**Comment by ElementalMP** [comment]
Should definitely be added, which server is this on?

**Comment by Rasgnarok** [comment]
Added /spark tps, closing once @ElementalMP confirms he's added the other command.

**Comment by ElementalMP** [comment]
This command is already added, but is broken as per a pixelmon bug. Closing.
