### ISSUE TITLE
Chimchar is locked, like it is in the day care, when it really isn't

### ISSUE THREAD

**Issue by mmoneypenny** [NebulaMC-GG/Support#1494]
I don't really know how to explain this bug. Basically, when the server went down earlier, it glitched the game, my Chimchar egg turned into a dragon fang, and now my Chimchar has the locked symbol in the PC, like it does when it is in the ranch block. However, it is not in the ranch block. It is completely stuck and nothing I have tried works (relogging, removing ranch block, moving pokemon around). I don't really care about the egg but I would really like for my chimchar to be unstuck.

IGN: Tyler_Moneypenny
Server: Orion

**Comment by Menno165** [comment]
I unlocked all of your ranches, issue should now have been taken care of.
Have a pleasant day on the server :)

Menno
