### ISSUE TITLE
Missing Moderation Commands via Trial Mod 

### ISSUE THREAD

**Issue by zTsuno** [NebulaMC-GG/Support#1500]
/tp does not work, and when typed by itself it asks to refer to /tpa. You can /endbattle yourself but not another. It also says permission node missing for /thru. No permission for /top. And no perms for /tphere.

**Comment by MissElyri** [comment]
Are you online right now? I can go over these and fix them before work. Or try.

**Comment by MissElyri** [comment]
With the help of Lieren, I have fixed the following commands for their respective roles:

Helpers:
/tppos - Allows the teleport of [x] [y] [z] coordinates
/endbattle (player) - Allows you to end battle another user

Trial Mod:
/top - Teleports you to the top block of the block column you're standing on
/thru - Allows you to go thru through walls of a certain width
/jump - Allows you to jump to the position your curser crosshair is on
/tphere (username) - Force teleports a user to your current position.

If you find anymore commands that do not work, please let me know.
