### ISSUE TITLE
Fly still working after 2 hours, Rune rank

### ISSUE THREAD

**Issue by redx10** [NebulaMC-GG/Support#1501]
Hi, So essentially, I have unlimited fly right now. Im not sure why, but when i used the /unlockfly command, its still going up to now, i believe i used it at around 12:00 pm est and now its 7:50 est. Im unsure what could have caused this, so i hope its a easy fix. 
Again, my ign is Valirus, and my discord is vali is invalid #4334.
Edit: So i just found out when i first join its still off. But when i go to spawn and rtp double tapping makes me fly again?

**Comment by MissElyri** [comment]
Awesome. I'll go ahead and close this for you then. If rhe issue returns feel free to put in another ticket!
