### ISSUE TITLE
Game crashes when breaking a PC

### ISSUE THREAD

**Issue by Squidammo** [NebulaMC-GG/Support#1506]
Hey, everytime I place a PC to store a pokemon in it, my game crashes but there's nothing in the ''crash-reports'' happened 2 times now, one in the nether and one in the overworld, nothing much else to say about this. Have a nice day :)

Edit: The power weight Item for HP ev training also gives us attack Evs, we can't train our HP evs without getting attack which is annoying, thanks for looking into this too :D

**Comment by HackuJacku** [comment]
This is currently a bug of Pixelmon 9.0.3 annoyingly. We are unable to do anything until the next release annoying. 

I've also forwarded the EV item issue onto one of the Support members for testing. Would recommend joining the discord.gg/pixelmon Discord and watch #upcoming-changelogs to see when it's fixed.
