### ISSUE TITLE
incorrect item count and a duplicate in vote crate rewards.

### ISSUE THREAD

**Issue by Vavalur** [NebulaMC-GG/Support#1507]
Great balls and pokeballs give you 10 when all other balls give 16. Two 16 premier ball rewards in the pool. 

![Screenshot_10](https://user-images.githubusercontent.com/107285589/175685787-604008f5-0de9-4e66-9089-8299459ac4c2.png)
![Screenshot_11](https://user-images.githubusercontent.com/107285589/175685958-72eee8dc-f262-47b8-bba7-5594ee672248.png)

**Comment by HackuJacku** [comment]
The Great and PokeBall amounts is intended. I have however removed the second Premier Ball reward. Thank you for the report :)
