### ISSUE TITLE
Apparently I duplicated Growth Modifiers

### ISSUE THREAD

**Issue by FoxArcher** [NebulaMC-GG/Support#1508]
Spent over 60 dollars in astral crate keys, got at least 6 cosmetic kit modifiers. Now two of the growth modifiers that i have left are showing up as duplicated. I just wanna make my pokemon tiny.

**Comment by FoxArcher** [comment]
Both growth modifiers that i have apparently show the same UUID. Cosmetic Kit comes with Growth, Gender, and Ball modifiers. I still have 6 gender mods (and I know that i have at least used 2 apart from the 6 I have left). I have made all 6 party pokemon microscopic, but the last two growth mods i have now are duplicates of each other. Idk how they "duped" but the number of growth  modifiers I have didn't increase, the items are just identical now.

**Comment by HackuJacku** [comment]
Forwarded to Val to look into :) Once the issue is sorted, we can refund you

**Comment by FoxArcher** [comment]
I noticed on a form modifier that when i shift clicked it into a chest, the "enchanted glow" was taken off the form modifier. dont know if this is something that may have to do with "duping"

**Comment by Rasgnarok** [comment]
Refunded you Fox, your two growth modifiers are now in your inventory.
