### ISSUE TITLE
MISSING OMEN COMMANDS AND SHAYMIN MOVE RELEARNER UNACCESSABLE

### ISSUE THREAD

**Issue by LimitlessJoker** [NebulaMC-GG/Support#1509]
Hi so im missing a lot of Omen Commands such as /redeem fossil and i cant move relearn shaymin-sky because spawn is permanent NIGHT time

**Comment by MissElyri** [comment]
We need to specifically know what command(s) you are missing or do not have access to per your rank, aside from the one named, to help you easier.

**Comment by HackuJacku** [comment]
RedeemFossil is fixed from the next restart. If you could confirm, would appreciate it :)

**Comment by LimitlessJoker** [comment]
It works. Just missing some more and Shaymin move relearn thats inaccessible

**Comment by HackuJacku** [comment]
You haven't specified them so we can't fix them... :/

**Comment by Rasgnarok** [comment]
Please also remember to _not_ abuse capital letters on what is essentially a support tracker. You've been told several times to be patient, there's no need for you to continue to be so verbally aggressive.

What's the issue exactly with Shaymin please? Make ONE ticket per issue, and explain with context and username+servername. Closing this ticket as invalid.
