### ISSUE TITLE
Nether Portal doesn't work

### ISSUE THREAD

**Issue by LuciferAshh** [NebulaMC-GG/Support#1512]
Upon attempting to enter a nether portal that exists within my claimed territory, nothing happens, followed by a message appearing in chat saying, "The portal portal could not be created as it resides in a claim you are not trusted in. Try another area." As of atm due to this I'm unable to enter the nether.

![image](https://user-images.githubusercontent.com/107779800/175750184-6666cacc-db89-4457-b52e-68e0fd11aaad.png)

**Comment by MissElyri** [comment]
Coordinates?

**Comment by LuciferAshh** [comment]
Since my post I had chunks fix my portal for me. And he's also fixed several other peoples portals by going into them and doing something. Due to this my portal works fine now.

**Comment by MissElyri** [comment]
Fantastic, thanks for letting us know.
