### ISSUE TITLE
Shaymin Sky move relearner

### ISSUE THREAD

**Issue by Vavalur** [NebulaMC-GG/Support#1516]
Shaymin sky currently cannot relearn moves that are exclusive to sky form from the move relearners at spawn. As it is permanently night, which reverts Shaymin to their original form, so relearners do not give you options to relearn sky form excusive moves. This problem will probably also persist to any other pokemon that has form dependent moves and the form depends on time of day.

**Comment by CenizaRey** [comment]
Spawn worlds have been set to 7am on each server to resolve this. Thanks for the report!
