### ISSUE TITLE
Regional variants having the wrong movepool

### ISSUE THREAD

**Issue by sun6002** [NebulaMC-GG/Support#1517]
I feel that this is a known issue, but I thought I'd archive it here:

Alternate forms (Alolan, Galarian, Hisuian) have a glitched movepool and learn the moves of their generic variants.  This affects not just already-known moves, but also level-up moves:
![2022-06-25_12 45 00](https://user-images.githubusercontent.com/106930193/175789738-8da57c0f-c244-4839-be0c-f8feee74d530.png)

_Edit: I forgot to mention that the Vulpix here I got from a form change voucher. That's probably a huge difference._

**Comment by Rasgnarok** [comment]
Fixed in 9.0.4.
