### ISSUE TITLE
Solar crate gave nothing in return

### ISSUE THREAD

**Issue by Trashess** [NebulaMC-GG/Support#1520]
Everyone on the server got a key from voting and most got their rewards, but some people, myself included, didn't get anything.

**Comment by CaptainTCovenant** [comment]
If possible, do you remember what the items were that people were not receiving? 
And was it the same items other players said they got, or different rewards?
Which server might this have happened on?

**Comment by Trashess** [comment]
I remember there were at least 2-3 other people who did not receive rewards, and only one of them had supposedly won and not received the same reward as I did, the Megastone Crate Key. This happened on Orion. Apologies as I cannot remember what others were supposed to have gotten. @CaptainTCovenant

**Comment by MissElyri** [comment]
@Trashess Did the key ever get refunded? I know certain rewards aren't being given and it's currently being worked on. I can issue you a refund if you have not received one already.

**Comment by Trashess** [comment]
@MissElyri I did not get refunded yet, no. That would be great though!

**Comment by MissElyri** [comment]
Refunded. :)
