### ISSUE TITLE
Battle error with rough skin in nebula?

### ISSUE THREAD

**Issue by redx10** [NebulaMC-GG/Support#1522]
Hi, when i try and attack a druddgon on nebula, it returns a battle error. Singleplayer doesnt seem to have any errors. my best guess is rough skin thanks to lexy? Im looking for my battle errors right now, so i will add it later when i find it, Sorry!

My ign is valirus and discord is vali is invalid #4334

**Comment by Rasgnarok** [comment]
This needs testing and forwarding to https://pixelmonmod.com/tracker.php?p=2 directly.

**Comment by Rasgnarok** [comment]
https://github.com/NebulaMC-GG/Support/issues/1543
