### ISSUE TITLE
buystore solar key not distributing

### ISSUE THREAD

**Issue by Khrisstias** [NebulaMC-GG/Support#1523]
We reached a buystore goal on Orion and the key did not send out to anyone onlin
![2022-06-26_18 52 28](https://user-images.githubusercontent.com/37944220/175838860-7e2d93be-6d80-44a7-b9fd-5f7ef90cb7f4.png)
![2022-06-26_18 52 31](https://user-images.githubusercontent.com/37944220/175838864-40933875-01d6-4c4b-bfdf-954602a4c1f9.png)
e

**Comment by HackuJacku** [comment]
Waiting on a fix from the developer

**Comment by HackuJacku** [comment]
This bug is now fixed, thank you for the report :)
