### ISSUE TITLE
Pets cannot be summoned in hub.

### ISSUE THREAD

**Issue by Chunkkss** [NebulaMC-GG/Support#1525]
I have no permissions to summon my lovely pet cow.

![2022-06-26_18 47 43](https://user-images.githubusercontent.com/107234416/175841322-96d7c167-6b95-47ef-9ae9-5a0eeca00508.png)
![2022-06-26_18 47 45](https://user-images.githubusercontent.com/107234416/175841326-47874fa2-5108-41b1-bdf8-c5a96f5ccd22.png)

**Comment by CenizaRey** [comment]
Tested and seems to be working, closing
