### ISSUE TITLE
Dexranks not Showing Player Tags

### ISSUE THREAD

**Issue by GigaFang** [NebulaMC-GG/Support#1528]
Is appears that the dexranks do not update the player tags in accordance with how far along they are in their dexrank. My experience with this is that I have 49.94% of my pokedex completed according to the dexranks menu and have been able to claim the rewards for Premier, Poke, and Great ranks as intended; however my tag has remained "Premier." In addition to this the weekly kits might not be working either but I am not sure since the one-time rewards did take up a lot of inventory space and I was distracted sorting those out, might be worth looking into. If this needs to be a separate issue I can do that.

**Comment by Rasgnarok** [comment]
This is now fixed, closing.
