### ISSUE TITLE
/Kits not working

### ISSUE THREAD

**Issue by benb25504** [NebulaMC-GG/Support#1531]
when attempting to use /kit and/or /kits I receive a "You dont have permissions for that!" response from the server.

**Comment by HackuJacku** [comment]
Hi @benb25504! Can you provide me with the following please?

- What is your IGN?
- Which server is this?
- Which kit are you trying to claim?

**Comment by benb25504** [comment]
IGN: BEN25504
Server: Titan
Kits: Poke and Great

**Comment by Rasgnarok** [comment]
This should now be working as expected, closing.
