### ISSUE TITLE
[Ranks] Master Rank issues

### ISSUE THREAD

**Issue by EzelBerbier** [NebulaMC-GG/Support#1535]
I reached the master rank today, and some issues happened me when i redeemed it, those problems are:

- The rank in the name didn't update, i mean, the rank that appears in [  ] before the nick
- Didn't give me the dragon head
- Gave me 1 masterbal instead of two
- I don't have acces to redeem the master kit

I didn't test about the claim blocks or homes, so i can't say nothing if there is problem with those too.

The dragon head and the masterball was alreadey refunded. Hope this ticket help to fixed it. 

The problem happened on Atlas, and im miguipkv there, if thats help checking the code.

**Comment by EzelBerbier** [comment]
Hi. I'm here to improve this ticket due to a mod recomendation, cause i didn't notice in the beginning a misunderstund between the /dexrewards and the rewards explanation in the announcements. 

First of all, the announcement explain which rewards gives u every rank, and the ./dexrewards -at least with master rank- doesn't match with it, and that confused me with the rank reward issues of the master rank. So im here to clarified and see if that is a mistake or is a change made it after the announcement (in that case the problem is minor). 

The four points that i said before, only one is wrong: the dragon head, and that was a mistake that i made for that confussion (really sorry about that), the ./dexrewards doesnt say anything about that, but the announcement say that u will be rewarded with Dragon Skull (i didn't notice that is a different item exclusive from pixelmon). The other three are correct, a actual issues that for some reason doesn't work and fit with what the annoucement say. 

Now, the thinks that doesn't fit between the announcement and the dexrewards info, and im not sure about if it was a intentional change or wasn't added for some reason, but I think will be better if that is clarified soon to avoid this confussion. The ./dexrewards doesn't include the same items that are showed in the announcement: 

- Dragon Skull.
- 1 masterball (a extra one besides of the other 2)
- 24 Ultra Balls
- 30 Quick Balls
- 1 Beast Ball

Hope this help to solve the general problems of the master rank. I will try to speak with the admin that refunded me the dragon head to see what we do (deleted, returned or whatever) because that is not part of the reward. Any problem im miguipkv, player of Atlas and in discord i'm Ezel#1229 if the member of the staff needs to clarify something in private or whatever to help. Thanks for all btw, really great work with the ranks!

**Comment by Rasgnarok** [comment]
These issues are now fixed, thank you!
