### ISSUE TITLE
/f bugged message

### ISSUE THREAD

**Issue by itanomaly** [NebulaMC-GG/Support#1536]
When typing /f the following message is displayed:
![2022-06-27_19 19 56](https://user-images.githubusercontent.com/79589400/175988488-601c0daf-c122-400d-ad89-b19451dd93a2.png)

**Comment by itanomaly** [comment]
Apparently it happens when you claim a /dexrewards kit as well: 
<details>
![2022-06-27_19 23 39](https://user-images.githubusercontent.com/79589400/175989178-053c0964-882d-406c-b761-bbc65a87386a.png)
</details>

**Comment by HackuJacku** [comment]
@itanomaly which server is this please?

**Comment by itanomaly** [comment]
It happened on Titan, I didn't check the other servers.

**Comment by Menno165** [comment]
Closing the issue as it no longer seems to occur.
