### ISSUE TITLE
/redeemfossil bugs

### ISSUE THREAD

**Issue by FBIAgentTimmy** [NebulaMC-GG/Support#1537]
Text is broken, and it ate my omanyte fossil. 
![image](https://user-images.githubusercontent.com/52301897/176047970-cecd470a-c890-4207-b943-73e450106e2c.png)

**Comment by FBIAgentTimmy** [comment]
nevermind it just bugged my fossil out. Text is still broken tho

**Comment by HackuJacku** [comment]
@FBIAgentTimmy need a server please

**Comment by HackuJacku** [comment]
This issue relates to #1536. Although they are different messages, it's all the same plugin. Thanks for the report :)
