### ISSUE TITLE
Solar Crate Key Bugged

### ISSUE THREAD

**Issue by PickleRichard03** [NebulaMC-GG/Support#1538]
After I opened the crate I got no rewards.

This is on the server Atlas and my username is PickleR1chard

![Screenshot 2022-06-27 192912](https://user-images.githubusercontent.com/108308619/176053600-1943c1c1-765e-4e4e-87c0-6e41a2276a68.jpg)

**Comment by Rasgnarok** [comment]
Can we please have your logs of what you received?

**Comment by PickleRichard03** [comment]
When I opened it, nothing in chat appeared and my key disappeared. Unless it was flooded out by other people's logs since it was the vote party reward.

**Comment by MissElyri** [comment]
Your chat logs in your minecraft folder will have what you should've received even with a vote party or spam in chat going on. You'll just have to look for that specific day/time

**Comment by PickleRichard03** [comment]
![image](https://user-images.githubusercontent.com/108308619/176725124-f22e0dd1-8076-4ebf-ba72-38cb54be2a52.png)

I went through the logs and didn't find anything about me winning anything.

**Comment by MissElyri** [comment]
DM me on discord (Elyri#2065) the next time you're online and I'll hop on and just refund the key.
