### ISSUE TITLE
great ball dexrank isnt updating

### ISSUE THREAD

**Issue by hikuda** [NebulaMC-GG/Support#1540]
hi! my IGN is : Akuda

with the introduction of dexranks, I understand that there are bound to be troubles and I'm sorry to bother you guys with my own. I know this seems to be more common, but I'm stuck at "poke" rank although I have more than 10% of my dex filled. I was told to submit a ticket to see if this could be resolved.

Thank you guys!

**Comment by Rasgnarok** [comment]
Fixed! Next time make sure to add your server username!
