### ISSUE TITLE
/Unlockfly not working

### ISSUE THREAD

**Issue by buntnessel** [NebulaMC-GG/Support#1542]
The /unlockfly command from the Rune rank is currently bugged, using it results in a error message in chat (see attached screenshot)
![unlockfly_bug](https://user-images.githubusercontent.com/47994052/176277484-3cddf581-06fd-4cf4-b4a7-a2e4e972bc13.png)

Furthermore, using /fly after the /unlockfly results in a "you don't have permission" error message - but I that is likely the result from /unlockfly not working as intended.

**Comment by CenizaRey** [comment]
This has been fixed, closing
