### ISSUE TITLE
Battle Error using moves on some Togedemaru

### ISSUE THREAD

**Issue by ThirstyMichael** [NebulaMC-GG/Support#1543]
[B#756] 2022/06/28 15:36:34 [INFO]  [15:36:34] [Sound engine/ERROR] [minecraft/ALUtils]: Stop: Invalid parameter parameter value.
[B#756] 2022/06/28 15:36:34 [INFO]  [15:36:34] [main/INFO] [minecraft/NewChatGui]: [CHAT] A battle error has occurred! Check the console for details and report this bug to the Pixelmon developers.

Server: Orion
I believe it's related to this ticket, feel free to merge if it's a reposted ticket, in which case it affects Iron Barbs as well as Rough Skin
https://github.com/NebulaMC-GG/Support/issues/1522

**Comment by Rasgnarok** [comment]
This needs testing and forwarding to https://pixelmonmod.com/tracker.php?p=2 directly.

**Comment by Rasgnarok** [comment]
Has been fixed as of 9.0.6.
