### ISSUE TITLE
Master rank kit and missing claim blocks/homes

### ISSUE THREAD

**Issue by Cryptowu** [NebulaMC-GG/Support#1546]
A few hours after dexrank was released I ranked up to ultra and the 2696 claim blocks were not added to my total. The next day I got master rank and those 824 claim blocks were added but I don't have access to the kit. I also only have access to 9 homes with Aria and Master ranks.

Server: Orion
IGN: Cryptowo

![claims_kit@4x](https://user-images.githubusercontent.com/59404256/176350207-77462e30-6bb3-40cb-8c62-ed3e9658faf1.png)

**Comment by Rasgnarok** [comment]
Alright, synced your rank properly so Master is now enforced, which should fix the kit. Also added back the claim blocks that you were missing. Thanks for reporting!
