### ISSUE TITLE
Master Rank Weekly Kits + Homes Issues

### ISSUE THREAD

**Issue by NyuNight** [NebulaMC-GG/Support#1552]
![MasterIssues](https://user-images.githubusercontent.com/52724323/176547087-fc8ae1a1-898d-40fe-abee-0602b3303d6a.png)

When Master Rank was first decreased to the 90% threshold, I was able to claim my one time rewards but since that time I was unable to collect the weekly kit. The other thing I noticed was that homes were broken. This was broken since I first obtained Beast Rank but I had asked for that to be fixed and I was able to get some extra homes, this was increased to 11 homes later with a combination from my newer ranks and Jade Rank. I was able to set more homes but for some reason the maximum decreased to 6 homes.

IGN: NueNight
Server: Atlas

**Comment by Rasgnarok** [comment]
This should now be working as expected, closing.
