### ISSUE TITLE
Omen commands missing/not working

### ISSUE THREAD

**Issue by Vavalur** [NebulaMC-GG/Support#1553]
Titan Server

/tms {pokemon name} does nothing

/redeemfossil message format error
![Screenshot_17](https://user-images.githubusercontent.com/107285589/176553565-e61b83ba-5c67-4e62-af32-ea4ba510552d.png)
![image](https://user-images.githubusercontent.com/107285589/176554421-d241cef9-3305-4736-990a-d8c2a6802806.png)
![image](https://user-images.githubusercontent.com/107285589/176565630-5bddcc85-580e-465f-b384-e4df9bbc03fd.png)
![image](https://user-images.githubusercontent.com/107285589/176565653-eb8958ba-799a-4fd4-810a-89929413d23b.png)

/hiddenpower {slot #} does nothing

/se no perms
![image](https://user-images.githubusercontent.com/107285589/176554212-43f407d8-3241-4322-a7ab-f4709e87aed0.png)

/ride no perms to ride anything
![image](https://user-images.githubusercontent.com/107285589/176554574-90b008f7-b8d7-444e-b7af-bc04c5d64f00.png)

/repair have access to hand and all, but not armor
![image](https://user-images.githubusercontent.com/107285589/176554698-46f7cf38-6923-4dcc-b4f4-2e7c4d6ae3ea.png)

/textcolor unknown command
![image](https://user-images.githubusercontent.com/107285589/176554788-b406835a-7ad0-477c-a9be-2254dfbe192a.png)

/skin feature not allowed on bungee
![image](https://user-images.githubusercontent.com/107285589/176555276-4e9c3456-771a-480a-bac0-7a5af28ae5d0.png)

**Comment by Rasgnarok** [comment]
Fixed /repair armor and /repair hand

**Comment by Rasgnarok** [comment]
/se is signedit, was defaulting to a WE command. Fixed

**Comment by Rasgnarok** [comment]
Closing this ticket in favour of splitting the remaining dysfunctional commands.

**Comment by Rasgnarok** [comment]
https://github.com/NebulaMC-GG/Support/issues/1708
https://github.com/NebulaMC-GG/Support/issues/1707
https://github.com/NebulaMC-GG/Support/issues/1706
