### ISSUE TITLE
Random Legendary Reward from Astral Crate giving Normal Pokemon (Titan) 

### ISSUE THREAD

**Issue by Ooomalooo** [NebulaMC-GG/Support#1554]
![image](https://user-images.githubusercontent.com/68833425/176559718-88d8b04a-a10d-4925-9a1a-ed6303b2d653.png)

Me along with many others have run into the issue where the Random Legendary Pokemon reward from crates has been giving players regular pokemon instead of random legendaries. This gave me a Smoochum instead of a legendary for example.

I found when trying to refund other players the command /pokegive <player> random legendary also kept giving normal pokemon instead of legendaries so it might have something to do with that command.

**Comment by Rasgnarok** [comment]
Now fixed, closing
