### ISSUE TITLE
CMI doesn't recognize mod tools for /repair

### ISSUE THREAD

**Issue by Vavalur** [NebulaMC-GG/Support#1558]
![image](https://user-images.githubusercontent.com/107285589/176709472-1b49a257-4f0d-4d70-b18a-1d7876f75c31.png)

Unfortunately /repair only works on vanilla items. Maybe at some point write a small server side mod that would do the same thing as /repair, but for mod items?

**Comment by HackuJacku** [comment]
Will require a custom solution but forwarded to our development team :)
