### ISSUE TITLE
Wasted money on shrine

### ISSUE THREAD

**Issue by Konanimo** [NebulaMC-GG/Support#1560]
I wasted 60k on the Timespace altar, thinking I just use an Adamant Orb on it like on the bird shrines. It then says that I require a red chain to use the orb on it. I've never played a mainstream Pokemon game, so I had no idea this was a thing. There was no indication around the altar that I needed two items. The only thing the confirmation screen asked me is if I wanted to spend 60k on it. The required items should be listed on the confirmation screen so people don't get scammed out of their money. I'd like to request a refund of the money I spent on the altar if possible because of the circumstances above. 
IGN: Konanimo
Server: Titan
![2022-06-30_11 34 10](https://user-images.githubusercontent.com/107813595/176813044-a1cfacd9-214a-450b-b870-b46e092c1309.png)

**Comment by Rasgnarok** [comment]
Activating the shrine does not mean it gives you the items you require. It's now placed on a sign for clarity, but at the time, it was already a floating sign at the beginning of the altar room - you need the items required.
