### ISSUE TITLE
Way to see Hidden Power and IVS of an egg through Modifiers (growth in that case)

### ISSUE THREAD

**Issue by Squidammo** [NebulaMC-GG/Support#1565]
Hello, nothing much to say about this, screens and title will show mostly everything :D

![turtwig1](https://user-images.githubusercontent.com/77607566/176981097-6613b7b3-b4f2-4379-a705-3446972c5872.png)

![turtwig2](https://user-images.githubusercontent.com/77607566/176981102-c6a9cc9f-d544-4ef6-b294-dd8f4243b203.png)

![turtwig3](https://user-images.githubusercontent.com/77607566/176981105-3df0782c-3588-43b6-9b43-95f8346b0725.png)

**Comment by HackuJacku** [comment]
This bug is now fixed, thank you for the report :)
