### ISSUE TITLE
Wonky Chat when given Items from Cosmetic crate

### ISSUE THREAD

**Issue by FoxArcher** [NebulaMC-GG/Support#1569]
![image](https://user-images.githubusercontent.com/108157492/177016626-0722e2ad-f8b0-4ef1-bf80-c4c0558f5e91.png)

**Comment by FoxArcher** [comment]
![image](https://user-images.githubusercontent.com/108157492/177053192-6774f134-678a-4222-9f07-8c1fed8a8d5a.png)

**Comment by FoxArcher** [comment]
![image](https://user-images.githubusercontent.com/108157492/177054130-46b8c4e6-233f-4b29-ad67-f1db968ea4de.png)

**Comment by FoxArcher** [comment]
![image](https://user-images.githubusercontent.com/108157492/178087477-33cf4fa9-3e03-42da-bcef-57925aa8e593.png)

**Comment by FoxArcher** [comment]
![image](https://user-images.githubusercontent.com/108157492/183099487-7205401d-05c2-4794-8932-9d36ef14317c.png)

**Comment by HackuJacku** [comment]
All the following formatting issues will be fixed for our upcoming crates update! Thank you for reporting this :)

**Comment by FoxArcher** [comment]
![image](https://user-images.githubusercontent.com/108157492/185645803-42492969-8afc-4fce-a944-ab0c4dcd0356.png)
