### ISSUE TITLE
Legacy Coupon/Gift card Not Received 

### ISSUE THREAD

**Issue by Deathwolf14** [NebulaMC-GG/Support#1572]
IGN: Deathwolf14_
Server: Orion

Enigma Legacy Rank i'm not to sure what to put here other than this 
![IMG_2032](https://user-images.githubusercontent.com/108595761/177026986-085264f5-6464-41bf-a296-81281e0f26c0.PNG)
![2022-07-03_01 00 20](https://user-images.githubusercontent.com/108595761/177027007-fb340af4-93e3-4036-9747-d2d3daecc62c.png)

**Comment by Deathwolf14** [comment]
Going to put this here aswell, I got a 10x Shiny and the flebebe I got wasn’t shiny, hoping you could change it to a shiny mon

**Comment by HackuJacku** [comment]
All Legacy codes have been sent out. If you have not received, please DM me on Discord (@Hacko#0001).
