### ISSUE TITLE
Pokedex Not Working

### ISSUE THREAD

**Issue by Centrii** [NebulaMC-GG/Support#1573]
IGN: Kiwizard101
Server: Titan

Some of my pokemon with my OT are not counted as dexed, even ones I bred and hatched myself.

![image](https://user-images.githubusercontent.com/81711140/177027847-62914f55-cbc0-4403-a8fd-37700553a415.png)
![image](https://user-images.githubusercontent.com/81711140/177027857-864ef426-0de5-4e48-a9cf-85722f8a8ce3.png)

**Comment by HackuJacku** [comment]
Non-Legendary Pokémon, regardless of OT, now count towards dex-progress. Only Legendaries do not and I am unable to reproduce your issue.
