### ISSUE TITLE
Luxury Dexrank unclaimable

### ISSUE THREAD

**Issue by FoxArcher** [NebulaMC-GG/Support#1575]
![image](https://user-images.githubusercontent.com/108157492/177033357-a170a783-a843-49c7-8c10-55a4a8766ba0.png)
@ 42% dex but can't claim luxury rank
Titan
FoxxArcher

**Comment by FoxArcher** [comment]
Player : "WestPaint15" also cannot claim Luxury rank in dexrewards
Server : Titan

**Comment by FoxArcher** [comment]
Player : PianoGuy1172
Server : Titan
attempting to claim great rank

**Comment by HackuJacku** [comment]
This issue should now be fixed but if not, please contact us via our Discord to ensure we can address it as soon as possible :)
