### ISSUE TITLE
Rank claiming not working

### ISSUE THREAD

**Issue by Trashess** [NebulaMC-GG/Support#1578]
At this point, I have gotten enough pokemon to complete 10% of the pokedex. I got the rewards from the Great Rank, but not the rank tag for chat itself nor the ability to use its weekly kit. It would very much be appreciated if something could be done about this.
![image](https://user-images.githubusercontent.com/108218315/177044364-a0a57d55-bebe-43d7-8c19-133456d009b8.png)
![image](https://user-images.githubusercontent.com/108218315/177044399-e9575c98-ff34-452a-9fa1-d947113a090f.png)

**Comment by HackuJacku** [comment]
This issue should now be fixed but if not, please contact us via our Discord to ensure we can address it as soon as possible :)
