### ISSUE TITLE
Dexrank not working

### ISSUE THREAD

**Issue by TinkerTrink** [NebulaMC-GG/Support#1580]
I completed a little over 10% of the dex but i'm not able to access the 'Great kit'.  I play on the Orion server and my user name is Tinker_Trink.

**Comment by Lieren-HuntGhosts** [comment]
Extending this to 25% Ultra, just completed 25,41% and have no access to Ultra, nor the reward or kit.

**Comment by HackuJacku** [comment]
When you next relog, this issue will be fixed. If not, please let us know via our Discord so we can fix this as soon as possible :)
