### ISSUE TITLE
Bergmite doesn't evo

### ISSUE THREAD

**Issue by emmuffin** [NebulaMC-GG/Support#1585]
Tried to evolve several bergmites, none of them will evo even with /trylevelevo

The conditions for evolving bergmite to a regular avalugg is just level 37 according to the wiki. Tried a variety of conditions like being in a snowy biome and relogging, nothing worked except Elyri pokediting it into an avalugg

**Comment by Khrisstias** [comment]
hello! was able to evolve bergmite to hisui avalugg in snowy taiga hills, normal bergmite needs ice spikes biome. The pixelmon wiki does not mention the ice spikes requirement.

**Comment by MissElyri** [comment]
@Khrisstias Can you cobfirm it Wlworks via server as well?If so, I'll close as nonissue

**Comment by Khrisstias** [comment]
@MissElyri it works!
