### ISSUE TITLE
Eevee affected by Sylveon evo bug

### ISSUE THREAD

**Issue by Denon10101** [NebulaMC-GG/Support#1586]
I attempted to evolve my shiny Eevee into a Sylveon. Met all requirements (High happiness, fairy-type move, sunflower plains) but she evolved into an Espeon instead. Would very much appreciate if she could be turned back into an Eevee if possible.

**Comment by Rasgnarok** [comment]
Hi! What's your username and server? I'll need you online for this.

**Comment by Rasgnarok** [comment]
https://pixelmonmod.com/tracker.php?p=2&t=17909

**Comment by Denon10101** [comment]
I am currently ingame; username is Denon101 and my server is Orion

**Comment by MissElyri** [comment]
Fixed the player issue; as this is already on the pixelmon tracker, I'll be closing.
