### ISSUE TITLE
Can't get beast rank rewards

### ISSUE THREAD

**Issue by emmuffin** [NebulaMC-GG/Support#1587]
![image](https://user-images.githubusercontent.com/83847439/177200380-823d2e35-33b9-4d21-a163-26480345dd52.png)
![image](https://user-images.githubusercontent.com/83847439/177200453-ab28c70f-8f8e-4e1b-9c41-52454d1329b2.png)
I just hit 80% dex but it says i already claimed beast rewards (and master too)

**Comment by HackuJacku** [comment]
This issue should now be fixed but if not, please contact us via our Discord to ensure we can address it as soon as possible :)
