### ISSUE TITLE
Tyrogue > Hitmonlee, Hitmonchan, Hitmontop suggestion

### ISSUE THREAD

**Issue by lexjo** [NebulaMC-GG/Support#1589]
As the evolutions of all 3 of tyrogue's evos seem to be bugged, would it be possible to change the evo requirements for the moment to something like levelling up with a power bracer held for hitmonlee, levelling up with a power belt for hitmonchan and levelling up to 20 with no item for hitmontop

**Comment by Rasgnarok** [comment]
Need this reported to Pixelmon, but in the meantime,
- Updated Tyrogue evolution method to Hitmonlee by trading while holding a Power Bracer. 
- Updated Tyrogue evolution method to Hitmonchan by trading while holding a Power Belt.
