### ISSUE TITLE
DexRewards: Can't claim ultra kit

### ISSUE THREAD

**Issue by Shadowall** [NebulaMC-GG/Support#1590]
Just achieved ultra on dexrewards and can't claim my ultra kit via /kits

-Acherous

**Comment by Shadowall** [comment]
Wanted to update that I am now the "nova" rank and can no longer claim aria kit but can claim nova.  Not sure if acting as intended or not

**Comment by HackuJacku** [comment]
Heya!

> Wanted to update that I am now the "nova" rank and can no longer claim aria kit but can claim nova. Not sure if acting as intended or not
This is intended, it's for balancing reasons.





> Just achieved ultra on dexrewards and can't claim my ultra kit via /kits
> 
> -Acherous
This should now be fixed if you log on :) If not, please let us know via Discord.
