### ISSUE TITLE
Unable to /fly in hub

### ISSUE THREAD

**Issue by CaptainTCovenant** [NebulaMC-GG/Support#1591]
Making this as Elemental said everyone should be able to fly in the hub, however it gives 'You don't have permission!'

![Screenshot_135](https://user-images.githubusercontent.com/92965754/177221726-569a8de2-51f4-490f-83af-d2bead751b68.png)

**Comment by Rasgnarok** [comment]
No... we have parkour on the hub, @ElementalMP.
