### ISSUE TITLE
Power Weight item providing both 8 hp and 8 atk

### ISSUE THREAD

**Issue by Ieuan-Cat** [NebulaMC-GG/Support#1595]
I was EV training my sylveon on whismur and makuhita (which are supposed to give 1HP EV) and with the power item on I was getting 9 HP EVs as well as 8 ATK EVs, took the power item off and i only got 1 HP EV

**Comment by Ieuan-Cat** [comment]
have yet to test anything but the defense one for the same issue (defense one works fine) so it could be a problem with multiple power items

**Comment by Khrisstias** [comment]
Hello! I was testing this in singleplayer and have confirmed this is a pixelmon bug, please make a detailed ticket describing your issue here: https://www.pixelmonmod.com/tracker.php?p=2

**Comment by Khrisstias** [comment]
This was fixed as of 9.0.6. Closing.
