### ISSUE TITLE
Missing Omen Commands Part 2 

### ISSUE THREAD

**Issue by LimitlessJoker** [NebulaMC-GG/Support#1600]
Currently missing log messages command

**Comment by HackuJacku** [comment]
What happens when you use `/logmessages choosegroups|custom`, @LimitlessJoker?

**Comment by Rasgnarok** [comment]
![image](https://user-images.githubusercontent.com/18584380/183141140-8797c6f5-9240-46fc-9d9c-29c2238462e6.png)
Using /logmessages choosegroups shows a book with unreadable colours. Otherwise, the command works.
