### ISSUE TITLE
Missing white Basculin evolution

### ISSUE THREAD

**Issue by Squidammo** [NebulaMC-GG/Support#1601]
I tried to evolve my White striped basculin in a normal way, it didn't work, I then asked mods to force evolve it and they said ''that the evolution didn't exist'', Basculegion seems to not be in the code yet, at least not as a Basculin evolution

**Comment by CenizaRey** [comment]
White-Striped Basculin now evolves by right-clicking it with a Reaper Cloth. Closing.
