### ISSUE TITLE
/hunts not saying what i won

### ISSUE THREAD

**Issue by Khrisstias** [NebulaMC-GG/Support#1608]
I did a rare hunt and got porygon, had no idea until i checked my inv. Same when i got an evo stone from an uncommon hunt.

**Comment by HackuJacku** [comment]
I'm unable to reproduce this bug. Please can you provide the server and username to refund to, @Khrisstias?

**Comment by MissElyri** [comment]
@HackuJacku there's nothing to refund. They got the items, it dmjust didn't say in chat what they got.

**Comment by HackuJacku** [comment]
Added a message in chat which tells you what you received after you complete a hunt.
