### ISSUE TITLE
/hunts giving double money?

### ISSUE THREAD

**Issue by Khrisstias** [NebulaMC-GG/Support#1609]
![2022-07-07_16 33 42](https://user-images.githubusercontent.com/37944220/177875204-6cdb2e04-724c-4e8d-9227-4d0eb00b5038.png)

**Comment by Vavalur** [comment]
There messages are also broken
![image](https://user-images.githubusercontent.com/107285589/177895481-496db28e-d383-43a6-9aba-685ddb95935a.png)

**Comment by PrimalCyndaquil** [comment]
This will be fixed by Hacko when he returns from holiday.
