### ISSUE TITLE
Gligar spawning during day

### ISSUE THREAD

**Issue by Khrisstias** [NebulaMC-GG/Support#1610]
Minor issue, was already fixed in pixelmon according to changelogs all it needs is a JSON refresh
![2022-07-07_21 07 31](https://user-images.githubusercontent.com/37944220/177902844-f9d4fe38-5146-4545-93ae-d64d7e477d98.png)

**Comment by Rasgnarok** [comment]
Should already be working fine, we don't datapack Gligar's spawn file.
