### ISSUE TITLE
Dexrewards Give Blue Mending Books Which are Non-functional

### ISSUE THREAD

**Issue by GigaFang** [NebulaMC-GG/Support#1611]
As the title says, the dexrewards for Master rank have a Mending book reward, but this book is bugged/not the correct version. By "Blue" book I mean the color of the name "Enchanted Book" when hovering over the item. It should look yellow and not blue in order to function properly.
![image](https://user-images.githubusercontent.com/108248340/177906196-bb64c5cd-9f1d-4ce1-b5ba-a6633700e8e9.png)
In this image you can see me attempt to put this book on a vanilla diamond shovel with no output shown on the anvil (output is barely visible behind gui).
![image](https://user-images.githubusercontent.com/108248340/177906499-294b6bac-ed35-4d1a-a518-2a65965048af.png)
In this image I have moved the cursor so you can see more clearly there is no output.
![image](https://user-images.githubusercontent.com/108248340/177906707-1c000135-f505-4e82-8473-e2bba685d114.png)
In this image I have put in a normal Mending book (yellow) to show what it should look like, the other enchantments are there because this book was fished up.

To fix this, you have to change the Enchanted book reward for Master rank to be a proper yellow one instead of a blue one. Cursory research led me to this thread on the topic which may be helpful https://www.spigotmc.org/threads/spawned-enchanted-books-wont-work-with-anvils.306557/

**Comment by lolanonymous** [comment]
mod note: manually refunded him the mending books.

**Comment by Rasgnarok** [comment]
Fixed, thanks for the report!
