### ISSUE TITLE
Legend hunt - no reward

### ISSUE THREAD

**Issue by dshannon519** [NebulaMC-GG/Support#1612]
as stated, completed legendary hunt 5 min prior to making ticket, did not appear to receive a reward, could be money but from prior hunts it usually states money gained in chat if it rolls that

**Comment by PrimalCyndaquil** [comment]
Fixed by Hacko - See the changelogs channel in our discord.

**Comment by PrimalCyndaquil** [comment]
This could not be reproduced.
