### ISSUE TITLE
/hunts Rewards - Orion

### ISSUE THREAD

**Issue by Deathnight7976** [NebulaMC-GG/Support#1614]
Everytime I complete an Ultimate hunt i receive the same exact reward. 
Which has been 12,000 coins (2 times per hunt), 1 Netherite block, 3 ranch upgrades, a ditto, and 3x XL Candies
It seems each player gets random rewards but it always repeats for the same player.

I've currently completed 4 ultimate hunts and its the same every time.

**Comment by Deathnight7976** [comment]
The Epic /hunts distributes only 1 of 2 listed silver Ras' lens upon completion

**Comment by PrimalCyndaquil** [comment]
Fixed by Hacko - See changelogs in our discord
