### ISSUE TITLE
Vote Crate key rewards some not appearing

### ISSUE THREAD

**Issue by Resnive** [NebulaMC-GG/Support#1616]
I did my 6 votes and only got 4 of the 6 rewards it said I should have got pomeg berries for one of rewards and I had over half an inventory clear to receive these.  So not sure why they were not given to me? I got all 6 keys but only 4 rewards out of 6.

**Comment by MissElyri** [comment]
Do you have the chat logs from where you received rewards? We would want to know the other reward in question

**Comment by Resnive** [comment]
Not anymore due to timeliness of response or I would happily have provided
it.

**Comment by MissElyri** [comment]
The logs in your MC folder wi still have them saved based on day and time

**Comment by Rasgnarok** [comment]
We will not be refunding vote crate keys, as those are simply a failure on the website, not us. You can vote daily for a minimum of 6 times, we will not be refunding a missing set of keys when you get 6 ecery 24 hours for free.
