### ISSUE TITLE
Move Tutor for Deoxys is borked

### ISSUE THREAD

**Issue by BrennenChapman** [NebulaMC-GG/Support#1619]
When doing move tutor on deoxys it only gives the options for base form deoxys despite being the the other forms of it. not sure if its a pixelmon issue or nebula issue
![deoxys base move learn set](https://user-images.githubusercontent.com/24552190/178097028-eb1f552f-7f15-4b82-9fa2-75b9552e3505.PNG)
![Deoxys move tutor](https://user-images.githubusercontent.com/24552190/178097030-714fd008-3fcf-4864-81f0-dd2042c864e4.PNG)
.

**Comment by Rasgnarok** [comment]
This is a Pixelmon bug that we could fix on our side as well, assigning to @CenizaRey

**Comment by Rasgnarok** [comment]
Will need forwarding by someone else to https://pixelmonmod.com/tracker.php?p=2

**Comment by Rasgnarok** [comment]
Has been forwarded, closing.
