### ISSUE TITLE
PC Search functions

### ISSUE THREAD

**Issue by Deathnight7976** [NebulaMC-GG/Support#1620]
using search functions in the pc you can determine if an egg is shiny/ha by searching 
all s or all ha respectively. 
Screenies
![shinyegg](https://user-images.githubusercontent.com/17133410/178103523-8b5e8c0a-dda5-4859-9cb4-cbf461a4e093.png)
![shinyOshawatt](https://user-images.githubusercontent.com/17133410/178103527-27480e0f-8166-4184-a650-5abc13d028a4.png)
![pc_search_ha](https://user-images.githubusercontent.com/17133410/178103557-866dace2-5a3e-4b2e-9b9d-7413328323fa.PNG)

**Comment by Rasgnarok** [comment]
This was patched in 1.12 and wasn't on 1.16, will need forwarding to: https://pixelmonmod.com/tracker.php?p=2

**Comment by Rasgnarok** [comment]
Has been forwarded, closing.
