### ISSUE TITLE
Crate key mega thread

### ISSUE THREAD

**Issue by lolanonymous** [NebulaMC-GG/Support#1623]
If you used a key/didn't receive  a reward from your key, post with following template

Username:

Server:

approximate time:

Optional: Chatlog/screenshot:

**Comment by BrennenChapman** [comment]
![image](https://user-images.githubusercontent.com/24552190/178132936-56627d31-874e-4d23-8687-c6674f006160.png)

**Comment by BrennenChapman** [comment]
![image](https://user-images.githubusercontent.com/24552190/178257640-33e705ab-3dc0-4dc4-bdc8-77a24a2e9252.png)
Orion
Tottwin
6:47am CST

**Comment by Squidammo** [comment]
All infos are in this screen <3
![Scammedandsad](https://user-images.githubusercontent.com/77607566/178621429-bd70d575-a3d4-46e3-aa39-da45e13d69fe.PNG)

**Comment by MissElyri** [comment]
All the above issues are fixed from next reboot
