### ISSUE TITLE
Fishing crashes the game

### ISSUE THREAD

**Issue by mnky-frt** [NebulaMC-GG/Support#1626]
Tried fishing in the 9.0.5 update. It works in single player but not in NebulaMC. 
here is the crash report and log files
[crash-2022-07-10_19.03.40-client.txt](https://github.com/NebulaMC-GG/Support/files/9080042/crash-2022-07-10_19.03.40-client.txt)
[2022-07-10-2.log](https://github.com/NebulaMC-GG/Support/files/9080045/2022-07-10-2.log)

**Comment by Khrisstias** [comment]
Thank you for the report! There is a pixelmon tracker ticket for it. https://pixelmonmod.com/tracker.php?p=2&t=18545

**Comment by Menno165** [comment]
Closing issue as it should have been solved on our end.
If issue occurs again feel free to open it again

![image](https://user-images.githubusercontent.com/84038836/178602385-a8706fbe-00e1-4ec4-adef-1f2f052fb41f.png)
