### ISSUE TITLE
Quickballs bugged or were they nerfed?

### ISSUE THREAD

**Issue by mnky-frt** [NebulaMC-GG/Support#1627]
Ever since the 9.0 pixelmon update i feel that quickballs are either nerfed or bugged.
In pixelmon 8/minecraft 1.12 they were super reliable and you could quickball most things as long as they werent a legend or something super high leveled
in pixelmon 9/minecraft 1.16 i am struggling to quickball pokemon that should be easy to catch like lvl 5 caterpies, pidgeys, etc... however, i have been able to quickball some higher level pokemon like about lvl 60 or so but it doesnt seem very consistent.

I'm posting on here just to get some info as if they were nerfed or if there is a bug going on with them

**Comment by Rasgnarok** [comment]
Quick balls are absolutely bugged according to Pixelmon's own tracker, pending a fix from the mod, https://pixelmonmod.com/tracker.php?p=2&t=17547
