### ISSUE TITLE
- Important Bug Report -

### ISSUE THREAD

**Issue by oliverze1** [NebulaMC-GG/Support#1628]
Recently I've noticed that when taking drops from Pokémon / bosses certain items are now voided, for instance when I beat a Legendary Mega Slowbro I had individually taken the items I wanted, but I didn't get the stone plate. I realized that if I hit "_drop all_" instead you can avoid this bug. I just thought it would be good to spread this issue around. I also believe if you hit "take all" after beating a Pokémon in battle it might also void certain items, but I have not confirmed this.

**Comment by Rasgnarok** [comment]
Fixed as of 9.0.6, thank you!
