### ISSUE TITLE
FIshing up enchanted books

### ISSUE THREAD

**Issue by Izayoi-Aki** [NebulaMC-GG/Support#1631]
I have twice so far fished up an "Enchanted Book" but it doesn't have any enchantments on it, yet it still glows like it does. Hacko told me I should post about it here. I am on Atlas and don't know if it happens on the other servers but I do not have a fishing rod on the other servers.

**Comment by Rasgnarok** [comment]
Fixed as of the latest version of Pixelmon.

**Comment by FoxArcher** [comment]
PirateBae on Titan fished up an enchanted book with no enchant. Asked when and they said within the last week. Bug possibly came back.
