### ISSUE TITLE
Cant join 

### ISSUE THREAD

**Issue by Quadehar97** [NebulaMC-GG/Support#1632]
Ign Quadehar97 

I'm trying to join Atlas the one i play most and have rank but it keeps telling me " unable to connect to Atlas.please try again later "
I am able to connect to the others No problem I've restarted my launcher and that but no luck

**Comment by CaptainTCovenant** [comment]
It currently says you are connected to Atlas, which is bugged as per your message. Have you tried signing out of your mc acc, then re sign in?

If that does not work, the only way I know how to fix you is only when the server restarts (about 8ish hours from now).

**Comment by Quadehar97** [comment]
I was just trying to rejoin again I'm currently sitting in the hubnow

**Comment by Quadehar97** [comment]
Ok

**Comment by Rasgnarok** [comment]
We believe it's something to do with the networking code behind our server api/bungee, so let's see if some setting changes fix this. Keeping it open, though I know it's not an easy one to test.
