### ISSUE TITLE
Infuser bug -- colorful shake being made with the wrong berries

### ISSUE THREAD

**Issue by mnky-frt** [NebulaMC-GG/Support#1633]
I am infusing two berries: grepa and qualot. According to the wiki these should make a yellow EV juice that yields 32 defense EVS: https://pixelmonmod.com/wiki/EV_Juices

However, the two berries are producing a colorful shake instead:
![image](https://user-images.githubusercontent.com/85257491/178399980-28741e1e-c6ec-424a-9c29-6ef7f5a3fb36.png)

On the wiki it says this is how you make a colorful shake: https://pixelmonmod.com/wiki/Colorful_Shake but neither of the berries I am using are included in this recipe

**Comment by Khrisstias** [comment]
Hi! This is a known pixelmon issue, however it will likely not be fixed due to us scrapping the infuser in the future. https://pixelmonmod.com/tracker.php?p=2&t=18276
