### ISSUE TITLE
Landorous spawn

### ISSUE THREAD

**Issue by Blaius** [NebulaMC-GG/Support#1637]
There was a Landorous spawn in a Wooded Badlands Plateau, where I was. I looked around but never bothered to look up cause I didn't think they flew. No one said anything, so I was wondering if it was actually on me. It was at 11:01am CT 7/12
![unknown](https://user-images.githubusercontent.com/107210251/178545377-366fc12f-e2d4-4301-8185-3fb65382a335.png)

**Comment by fatyg5** [comment]
We can't check who it spawned on, and even if we could we wouldn't be refunding it or anything.
