### ISSUE TITLE
Crates Can Be Opened By 2 People and Only 1 Will Get the rewards

### ISSUE THREAD

**Issue by Deathwolf14** [NebulaMC-GG/Support#1639]
I'm Not sure how it works but occasionally people open a crate when my was "Spinning" and it wouldn't give me the rewards and instead the other player. Lost a Solar Key over this.
Not sure but when I was using a Vote Crate it bugged me to wait till next reset to open crates again, think this the reason why

**Comment by MissElyri** [comment]
Username and server, please? This issue has been fixed but I'd like to refund your key.

**Comment by HackuJacku** [comment]
Hello, this is fixed in the up-coming update to Crates.
