### ISSUE TITLE
Open a crate at the same time with another person for drop party and didnt get the reward

### ISSUE THREAD

**Issue by toofuriouz** [NebulaMC-GG/Support#1640]
So i have the latest.log open which relaunching minecraft which cause me not able find or upload the file as it is wiped. However i have a screenshot and posted it on discord prior to this
![image](https://user-images.githubusercontent.com/85075804/178603993-ee31d66d-53c1-463f-9d59-c518f21ab023.png)

**Comment by fatyg5** [comment]
Refunded.
