### ISSUE TITLE
Unable to use /hub or /orion

### ISSUE THREAD

**Issue by CaptainTCovenant** [NebulaMC-GG/Support#1648]
Hadn't noticed this till now, since im usually on Orion. 
Title says it all. In Titan/Atlas, you cannot use /orion to get to orion, you have to use /server orion. 
/hub is perm locked, however /server hub
![Screenshot_158](https://user-images.githubusercontent.com/92965754/179121173-cfe9c33b-a5c9-45a7-816f-5d892e79ca2d.png)
![Screenshot_159](https://user-images.githubusercontent.com/92965754/179121174-cb44437e-8e4a-4948-a310-3900d4ff896f.png)
![Screenshot_160](https://user-images.githubusercontent.com/92965754/179121175-719d8ae3-af56-4b87-8553-665dd41a14fd.png)
 works fine

**Comment by HackuJacku** [comment]
You are now able to use `/orion`. You'll be able to use `/hub` from the next proxy restart (next Tuesday).
