### ISSUE TITLE
No reward from Legendary hunt

### ISSUE THREAD

**Issue by Ph30nex** [NebulaMC-GG/Support#1650]
![2022-07-14_13 10 37](https://user-images.githubusercontent.com/109340822/179183071-bb221e15-9c5c-4e21-a073-f679bc6df348.png)

Completed a legendary hunt and no reward was given. My cash stayed the same, and no items were added to my inventory.

**Comment by Ph30nex** [comment]
Just happened again with an ultimate hunt
![2022-07-15_03 18 27](https://user-images.githubusercontent.com/109340822/179204172-2fbcbb02-b1cc-4da2-8c21-d026d67aa585.png)
![2022-07-15_03 18 04](https://user-images.githubusercontent.com/109340822/179204176-abd395b3-e212-408c-b87f-54781ba07850.png)
t

**Comment by HackuJacku** [comment]
This is now fixed from the next restart, thank you for the report! @MissElyri will handle you being refunded :)

**Comment by MissElyri** [comment]
@Ph30nex  I need your username and server whenever possible; I'll refund you next time we're both online

**Comment by Ph30nex** [comment]
I am Ph30nex on Orion. Been out of town, but I'll be online again now

**Comment by HackuJacku** [comment]
@Ph30nex - I've given you a random reward from the Legendary reward (it was a Blue Flute), which I have placed in your inventory. This bug has also been fixed, thanks for the report and sorry for the delay! :)
