### ISSUE TITLE
Can open a portal to Ultra Space using Solgaleo/Lunala

### ISSUE THREAD

**Issue by AbelVuong** [NebulaMC-GG/Support#1651]
can open a portal using their special abilities
<img width="368" alt="Screen Shot 2022-07-15 at 6 10 38 PM" src="https://user-images.githubusercontent.com/86174626/179212968-003ddeb1-1a18-4f50-82dd-ee0a9e04853f.png">

**Comment by Lieren-HuntGhosts** [comment]
You can't get into ultraspace, you still get sent back even if you try to /back. This was added to prevent people from going into ultraspace but wormholes still exist in the game. But there's no problem with that.

**Comment by AbelVuong** [comment]
I'm sorry but I just tried going in and I can enter the Ultra Space still no ./back needed. I can send a vid to prove that if necessary

**Comment by Lieren-HuntGhosts** [comment]
Please do. Also a screenshot should be enough.

**Comment by AbelVuong** [comment]
<img width="1440" alt="Screen Shot 2022-08-06 at 5 37 49 PM" src="https://user-images.githubusercontent.com/86174626/183245402-6b4a4034-3582-4f7a-adb9-6f8bf017ffa4.png">
<img width="1440" alt="Screen Shot 2022-08-06 at 5 37 45 PM" src="https://user-images.githubusercontent.com/86174626/183245406-51649483-ec3a-4630-ba4b-6352c9b93156.png">
<img width="1440" alt="Screen Shot 2022-08-06 at 5 36 14 PM" src="https://user-images.githubusercontent.com/86174626/183245422-74a2510a-f9c1-4e86-b06d-561f9fe17f55.png">
![Uploading Screen Shot 2022-08-06 at 5.36.29 PM.png…]()

**Comment by AbelVuong** [comment]
server Orion. it seem somone already abusing it and made a Platform here. since the last time I reported there was no platform
