### ISSUE TITLE
No reward from ultimate hunt completion

### ISSUE THREAD

**Issue by Cheesecake373** [NebulaMC-GG/Support#1652]
![Screenshot (153)](https://user-images.githubusercontent.com/109369400/179274805-324252cf-d661-4c3a-bdb3-0cb8c1a057c9.png)
I completed the ultimate hunt but never received anything from it. No money, mons, books, balls, or whatever. No chat saying I received anything, hope this can be fixed. Thank You. My username is Lxmon5

**Comment by manlybro2002** [comment]
same problem
![2022-07-17_19 44 27](https://user-images.githubusercontent.com/83971987/179420604-4b1ade05-d30c-4071-98d2-d465cb4a9f75.png)

**Comment by MissElyri** [comment]
This is currently an ongoing issue. We do have a megathread in support if for the next time you complete the hunt, take a screenshot of what you would've received and mod or admin will get with you soon to refund you your winnings. 

We also need to know what server you play on in this case, so we know where to go to refund. Cheers!

**Comment by Cheesecake373** [comment]
Hey, good info to know thank you, I'm currently playing on the Orion server.

**Comment by HackuJacku** [comment]
This bug is now fixed from the next reboot. @MissElyri will handle you being refunded if that is required :))

**Comment by MissElyri** [comment]
I have refunded @Cheesecake373 , however I need your username and server @manlybro2002 so I can refund you as well and close this tracker. :)

**Comment by manlybro2002** [comment]
manlybro2002
orion server

**Comment by HackuJacku** [comment]
@manlybro2002 - given you 2x Master Balls for completing the hunt. Enjoy :)
