### ISSUE TITLE
 Luxury rank- max Iv voucher - Orion

### ISSUE THREAD

**Issue by Darkassassin0** [NebulaMC-GG/Support#1656]
so I hit luxury dex rank and got an iv voucher and it didn't make my Pokémon unbreedable when I used it is it normal it didn't mention it was gonna make it unbreedable just wanted to make sure

**Comment by MissElyri** [comment]
Modifiers that make Pokemon unbreedable have been updated to have the flavor text that they make them unbreedable. If you would like a refund of either item/pokemon, please let me know. I'll need your original mon back, however. Feel free to DM me on discord. Elyri#2065
