### ISSUE TITLE
unable to claim Weekly Reward for DexRewards Ultra Rank

### ISSUE THREAD

**Issue by thenorthwind5498** [NebulaMC-GG/Support#1657]
![image](https://user-images.githubusercontent.com/57773613/179381936-a4878a3f-eb2d-4e68-9569-3a5ebf322ce7.png)
![image](https://user-images.githubusercontent.com/57773613/179381943-ea59fe75-ec1a-4a55-8458-07d5348dd269.png)

I reached the ultra rank for the dexrewards but i am unable to receive the award for it

**Comment by MissElyri** [comment]
We need your username and server to fix this issue. Please

**Comment by thenorthwind5498** [comment]
Sorry for the late response.  But I'm on the atlas server and the name is
thenorthwind5498. However,  there was a big update and it appears to be
working now.

**Comment by MissElyri** [comment]
Alright, sounds great. :)
