### ISSUE TITLE
Luxury to Dream Prefix/Kit Bug

### ISSUE THREAD

**Issue by CyberEnt1** [NebulaMC-GG/Support#1658]
Hey common bug here, I just hit 60% Pokedex completion and claimed the Dream rank. I received the one-time rewards but cannot redeem the /kit dream, and my prefix is also still Luxury. I play on Atlas and my ign is CyberEnt

**Comment by CyberEnt1** [comment]
![image](https://user-images.githubusercontent.com/109041979/179386664-7bf0af59-5767-4653-aef4-fd092f74975e.png)
![image](https://user-images.githubusercontent.com/109041979/179386669-7db20114-43f5-4c13-81eb-a0520edb66ac.png)

**Comment by MissElyri** [comment]
I'll be home Tuesday to fix your rank if it has not been fixed before then. (As I'm onholidsy right now)
