### ISSUE TITLE
Nickname limit

### ISSUE THREAD

**Issue by CaptainTCovenant** [NebulaMC-GG/Support#1659]
You can nickname for 3 letters on Orion server, when the others restrict you to 4 letters.
![Screenshot_169](https://user-images.githubusercontent.com/92965754/179387956-133836db-fe1e-43d2-94a8-b762afed373d.png)
![Screenshot_170](https://user-images.githubusercontent.com/92965754/179387957-038e12a6-4394-473c-91f5-2ef01a675ca7.png)

**Comment by HackuJacku** [comment]
This is now fixed from the next reboot, thank you for the report :)
