### ISSUE TITLE
Vote Party Key ate without giving anything 

### ISSUE THREAD

**Issue by JuniperSpringstick** [NebulaMC-GG/Support#1663]
Yesterday I got a vote party key and went to redeem it but it didnt give me anything. Here are the logs and photos of the chat.
[techniclauncher_2022-07-17.log](https://github.com/NebulaMC-GG/Support/files/9136739/techniclauncher_2022-07-17.log)
![2022-07-17_19 10 49](https://user-images.githubusercontent.com/108998202/179645199-b3a05b99-c0a6-45f7-b827-12d841c2ce54.png)
![2022-07-17_19 10 40](https://user-images.githubusercontent.com/108998202/179645201-b0663a5c-afa9-4f6d-9b21-0d2a6f56544a.png)

**Comment by Chunkkss** [comment]
Make sure to note your username and time that this happened. Makes it easier to search through logs for admins.

**Comment by JuniperSpringstick** [comment]
JuniperSpringsti
Atlas ..... I did this yesterday on your support channel

**Comment by MissElyri** [comment]
Dm me on discord when you're next online. I'll refund your key. Closing for now. Elyri#2065
