### ISSUE TITLE
Rune to Omen Upgrade Purchase Issue

### ISSUE THREAD

**Issue by StrideMate** [NebulaMC-GG/Support#1664]
So I just bought rune to omen rank, I received the money and the keys however my rank and perms where deleted I have legacy on the server and can't access fly. IGN: Stridei
![Screenshot_20220719-124434_Outlook](https://user-images.githubusercontent.com/78794976/179654868-80d1fb08-5730-465e-9568-c278aa1b145b.jpg)
![20220719_124534](https://user-images.githubusercontent.com/78794976/179654875-19cea348-6865-4a30-a326-7c4f6e08a936.jpg)
![20220719_124541](https://user-images.githubusercontent.com/78794976/179654877-0aeb7d32-3c59-44c8-864a-9d03f896f590.jpg)
![20220719_124556](https://user-images.githubusercontent.com/78794976/179654878-39f476aa-d390-48fc-8680-266cc2b4cf41.jpg)
i

**Comment by PrimalCyndaquil** [comment]
Have given you the correct rank. Will leave open as this still needs to be fixed for anyone else that does this specific upgrade.

**Comment by Rasgnarok** [comment]
Known issue, Tebex side. Closing
