### ISSUE TITLE
Ultimate Hunt Completed, no rewards

### ISSUE THREAD

**Issue by innqmorato** [NebulaMC-GG/Support#1666]
Just completed an ultimate hunt on orion server, nick : innqmorato , didn't get anything neither dittos or money
![2022-07-20_02 05 37](https://user-images.githubusercontent.com/109287888/179868458-033039ca-6ddf-4bfa-ab91-7a2e2ad012ea.png)

**Comment by HackuJacku** [comment]
Fixed from next reboot. You don't get both the Dittos or money, it's one or the other, randomly selected.

**Comment by MissElyri** [comment]
Refunded
