### ISSUE TITLE
Bellossom's rarity is 0.5 -- shares same rarity as Ditto

### ISSUE THREAD

**Issue by mnky-frt** [NebulaMC-GG/Support#1667]
I saw the message on discord about Duraludon's rarity being changed from 0.5 to 6.0

This reminded me that according to '/wiki bellossom rarity' it's rarity is 0.5. I wasn't sure if this was intentional but after reading the message on discord I feel like it is not. I think like this pokemon should not be as rare as Ditto because Ditto (and Spiritomb as well) also has a rarity of 0.5 according to the /wiki

**Comment by BrennenChapman** [comment]
you can evolve gloom into bellossom with a sun stone.

**Comment by mnky-frt** [comment]
oh right i completely forgot lol
still pretty rare tho
