### ISSUE TITLE
Did not get Rune rank.

### ISSUE THREAD

**Issue by Grunt064** [NebulaMC-GG/Support#1670]
Hello! I recently bought Rune rank, did not receive the tag or any permisions. I got the money and the 2 keys that came with the Rank. Thank you!
![image](https://user-images.githubusercontent.com/89787272/180060335-965edfcf-77a1-40ec-8713-56312275c922.png)

**Comment by MissElyri** [comment]
To fix this, I need your username and server please. :) Or you can just message me directly via Discord for a faster response; Elyri#2065

**Comment by MissElyri** [comment]
@Grunt064 Was this issue ever fixed for you? Just wanting to check in.

**Comment by Grunt064** [comment]
Yes it was thankfully thank you!

**Comment by HackuJacku** [comment]
Closing as this is resolved :)
