### ISSUE TITLE
Fishing Pokemon with wonky chat in pokemon name

### ISSUE THREAD

**Issue by FoxArcher** [NebulaMC-GG/Support#1671]
![image](https://user-images.githubusercontent.com/108157492/180271755-a0b8d4a7-8377-49a4-819a-adcb315a119e.png)

**Comment by Lieren-HuntGhosts** [comment]
This was because it was a pokehunt target. It will be solved when the next reset happens.

**Comment by MissElyri** [comment]
Yeah, I have a Tynamo like this as well; Closing for now as it has been fixed pending restart.
