### ISSUE TITLE
Cosmic Crate - XP candy inconsistencies

### ISSUE THREAD

**Issue by Deathnight7976** [NebulaMC-GG/Support#1673]
On Atlas cosmic keys drop 8x L xp Candy:
![cosmic atlas](https://user-images.githubusercontent.com/17133410/180356220-a16a3334-018d-4121-b81a-6c0238a3e1e9.png)

Meanwhile the storepage says it should drop 8x XL Candy:
![cosmic storepage](https://user-images.githubusercontent.com/17133410/180356266-ad29e877-f357-4434-a113-24aecee20463.png)

And ingame on Orion/Titan the crate displays 16x XL candy:
![Cosmic Crate](https://user-images.githubusercontent.com/17133410/180356539-73727c0d-c2c1-4848-9bfd-f79b337d9798.png)

**Comment by HackuJacku** [comment]
Hello, this is fixed in the up-coming update to Crates. @MissElyri - could you refund to correct type/amount please?

**Comment by MissElyri** [comment]
Fixed in upcoming update. Closing for now.
