### ISSUE TITLE
Ultimate hunt don't give any rewards 

### ISSUE THREAD

**Issue by AbelVuong** [NebulaMC-GG/Support#1674]
<img width="1440" alt="Screen Shot 2022-07-22 at 1 46 49 PM" src="https://user-images.githubusercontent.com/86174626/180380623-ed65ce3b-7c2e-4c4f-a2ec-4417021e05be.png">
my money stay the same and I didn't get any items

**Comment by AbelVuong** [comment]
username: thangtaolao server: Orion about 2 PM JST I thinks

**Comment by MissElyri** [comment]
Refunded 12,000 coins. 
![image](https://user-images.githubusercontent.com/78369601/180594716-df725529-4b4e-49cc-a879-efb72c24e633.png)
