### ISSUE TITLE
Can't catch mons in raid dent 

### ISSUE THREAD

**Issue by AbelVuong** [NebulaMC-GG/Support#1675]
<img width="1440" alt="Screen Shot 2022-07-22 at 11 46 39 PM" src="https://user-images.githubusercontent.com/86174626/180495257-873acc98-cd3b-47bf-94df-048f28f9ca90.png">![image](https://user-images.githubusercontent.com/86174626/180495312-fc412881-3219-4c56-af0d-862e7f98cc46.png)

**Comment by AbelVuong** [comment]
the button won't works despite clicking it many time

**Comment by MissElyri** [comment]
I can refund you the ditto, but the meowth is a common enough spawn that it can be found in the wild. I'll need your server and IGN though.

**Comment by AbelVuong** [comment]
ah yes ty I only need Ditto to be refuned. IGN: thangtaolao server: Orion

**Comment by MissElyri** [comment]
Done and done. :)
