### ISSUE TITLE
Baby Mons Breeding

### ISSUE THREAD

**Issue by innqmorato** [NebulaMC-GG/Support#1677]
I breeded an ot piakchu with a non-ot ditto in order to get a pichu, got it from egg hatching but didn't count it in pokedex, same story for a jynx breeding and a smoochum egg

EDIT: babies don't count on dex in the moment of hatching but only when you get them to pc

**Comment by Rasgnarok** [comment]
That sounds like a Pixelmon bug, it'll need to be confirmed and reported here: https://pixelmonmod.com/tracker.php?p=2

**Comment by Rasgnarok** [comment]
Cannot be reproduced, closing.
