### ISSUE TITLE
freddypwner ban appeal

### ISSUE THREAD

**Issue by freddypwner** [NebulaMC-GG/Support#1678]
I used to play on this server religiously back in 2018-2021, taking part in all sorts of events and community stuff and everything. This was my favorite server ever, I genuinely think it's the best designed Minecraft server I have seen. Whenever I beat any of the player gyms, especially the Ione one, I was super toxic to the Gym Leaders because I thought I was better than them or something. I look back at myself that year and a half ago and cringe a lot, because that's just such a stupid thing to do. Like, it took me so many tries to beat them a single time, and I think my cockiness came from a place of a lack of self confidence. I had to put down others to make myself feel better about myself. I have been humbled and built up anew since then, and my mindset has changed to one of "everybody can teach me something," and I want to be a part of this wonderful community again. I am an entirely new person and I have discovered all sorts of passions in my real life that keep me happy and stress free, and I feel like I can leverage that positive energy to be a source of happiness in this community. Please consider unbanning me and letting me take part in the amazing server you all have worked so hard to create.
I have had one ban appeal denied before about a year ago.

I am so sincerely sorry,
Kevin.

**Comment by freddypwner** [comment]
I'm going to add more onto this.
Back in 2018 when my dog died, I turned to this server as a coping mechanism. For two weeks, I woke up, got on Oblique, and slept. I occasionally ate when I was super hungry, but talking with people in this server like Head Builder at the time Sly and being in such a generally caring and kind atmosphere as this server allowed me to process through those grievous emotions much more easily.
The Summer after my 8th grade year, I think it was 2019, I had some traumatic stuff happen IRL. Again, this server was what I turned to a lot. I had really nobody in real life besides my parents, and this server helped me get through that horrible Summer.
In both of these instances, after the time period, I just immediately shook it off. I felt better. I didn't show grief for my dog because I think I just kind of speedran the grieving process by staying in denial until God just said, "Ok you know what, just skip him ahead to acceptance." (This is very shortened and there was definitely more than what I wrote, I used hyperbole for comedic effect.)
These two instances are intended to elicit sympathy from the reader and illustrate how much this server really means to me. I would not be the person I am today without the experiences I had on Oblique.
And on top of all of that, why I keep coming back, begging for an unban, is just because I genuinely believe this is the single best Pixelmon server out there. Sure, there are others, many many others, but I don't care. You guys at Oblique, now Nebula, were my home away from home, my second family. I wouldn't be so attached if the moderators weren't so damn fair and transparent and honest and just, and they gave me multiple chances and were so fair and they told me exactly what I did wrong, and I love that. It's such an amazing system. Being on the recieving end of this system just shows me proof of how well oiled and compassionate people like Katadreme are even when I have clearly done horrible things. That sort of firm compassion just makes me want to come back even more, and I so badly want to come back.
The two main points of prison are punishment and rehabilitation. When you do a crime, you do the time, and hopefully come out a better person at the end. My time away on ban from Nebula has been time for me to improve and become a better person, and I sincerely believe I have served my sentence. I have done the crime, and I served my time, and I'm ready to come back as a member of NebulaMC society again.
My username is freddypwner and my Discord is SoYeah,ImAGamer#2585
How much time must I serve until you believe I can be better?

**Comment by MissElyri** [comment]
I have looked over your past actions and will have to agree. 4 years is a *long time* for someone to become a better person. I'm giving you the benefit of the doubt as well, because you were so young at the time (In 8th grade, via your claims.). To be fair, the actions you portrayed aren't the worst I've ever seen, however the number of times it happened is what bothers me a bit. 

I'm one to give benefit of the doubt, I truly see the difference between then and now. I'm going to go ahead and unban you as well as DM you on discord to make you aware, as you may see that sooner than the reply for this. 

Welcome back to Nebula! Please be as kind as you portray here, and be sure to read the /rules for me to catch up on anything you may have missed as we have updated some of the rules since the last time you were here!
