### ISSUE TITLE
Pokémon sometimes evolve into themselves.

### ISSUE THREAD

**Issue by Augie279** [NebulaMC-GG/Support#1679]
[Screenshot](https://i.imgur.com/kGlYUVA.png)
This seems to prevent the Pokémon from evolving again, but I think it can be worked around by leaving and rejoining.
[latest.log](https://github.com/NebulaMC-GG/Support/files/9175077/latest.log)
[2022-07-23-1.log](https://github.com/NebulaMC-GG/Support/files/9175078/2022-07-23-1.log)

**Comment by Rasgnarok** [comment]
Known issue from Pixelmon itself, it's been forwarded already.
