### ISSUE TITLE
Rank Upgrades occasionally not working.

### ISSUE THREAD

**Issue by PrimalCyndaquil** [NebulaMC-GG/Support#1683]
On two occasions so far, rank upgrades purchased by players seem to fail to actually upgrade the players rank.
The player will instead have their current rank removed, but won't get their new rank added. Probably an issue with whatever commands the store is running when purchasing these ranks.

**Comment by Resnive** [comment]
I'd also like to add to this.  Cosmetics for the ranks are not always being added to the player's options this has happened to myself and probably some others.

**Comment by Rasgnarok** [comment]
It's actually a Luckperms issue, it's been reported to the author but since we're running a hybrid, it's not at all within their scope. We'll need to make a different system for this entirely. Closing as an internal issue.

**Comment by Rasgnarok** [comment]
https://github.com/LuckPerms/LuckPerms/issues/3454

**Comment by Rasgnarok** [comment]
Closing as this has been forwarded to the plugin author. We might have a temporary work around by adding the permission node of the group itself on a delay. Thanks for the ticket!
