### ISSUE TITLE
Invitefriend is very broken

### ISSUE THREAD

**Issue by GalaBats** [NebulaMC-GG/Support#1684]
A now-resolved issue was where I did not get rewards for a friend reaching their 12 hours after I invited them. I now have those rewards, that is resolved.

**But then it broke more!** I can now no longer invite ANYONE because of that, nor can I remove the invite. I have like three other friends to invite and the system is broken

Please help me

**Comment by GalaBats** [comment]
i fucking left bc the community is terrible and 'Sakura' literally **deleted someone's fucking house** after ONE WEEK of them being gone

Respectfully your server is a fucking joke

**Comment by MissElyri** [comment]
I'm sorry that something that should work flawlessly right now, isn't for you. However if you'd like to literally provide any kind of context for the situation at hand, that'd be fantastic.

As far as "Sakura" deleing a house, I'd like some context to this too, as it involves one of my helpers, and ironically something they're not (or should not) be able to do.

**Comment by GalaBats** [comment]
I'm not exactly sure why it matters as me and my four friends have entirely decided to abandon the server for the ridiculous ranking system, the terrible community, constant mistreatment by staff (we've only been here like a day), and frankly the really low legend spawnrate.

We can find a better server. Ask your helpers yourself, me and my ten other friends won't be apart of this.

**Comment by CenizaRey** [comment]
Ratio
