### ISSUE TITLE
Get it together.

### ISSUE THREAD

**Issue by GalaBats** [NebulaMC-GG/Support#1690]
![image](https://user-images.githubusercontent.com/110071778/181427132-3ed739a7-b305-44f1-97a5-efcff57645f4.png)
Glad to see your staff are fucking children.

**Comment by CenizaRey** [comment]
Ratio (2)

**Comment by GalaBats** [comment]
Seriously? Grow up. You're already supporting a basically pay-to-win server, I doubt you aren't paid.
