### ISSUE TITLE
Dexrewards - Missing pokemon gui function counts seen pokemon

### ISSUE THREAD

**Issue by Deathnight7976** [NebulaMC-GG/Support#1693]
The /dexrewards missing Pokemon GUI option removes Pokemon that you've seen from the list of remaining Pokemon.

Screenies:

Dex Entry for Keldeo #647
![keldeodex](https://user-images.githubusercontent.com/17133410/181872277-3b5b3123-95fa-4ddd-a83e-18b6292bfa6c.png)

Missing Poke Gui 1:
![645](https://user-images.githubusercontent.com/17133410/181872312-5bf625c1-1a99-4164-87b8-1ae5e632d2bc.png)

Missing Poke Gui 2:
![648](https://user-images.githubusercontent.com/17133410/181872321-7c5201b2-1ed2-4446-ad0d-0a0d565e7815.png)

**Comment by HackuJacku** [comment]
Yes, this is an intended feature and not a bug.
