### ISSUE TITLE
Donation Reward Not given to player

### ISSUE THREAD

**Issue by TheWeas** [NebulaMC-GG/Support#1695]
I recently bought jade rank along with 2 astral keys at 17:05:40 on 7/31/22. Once I logged into nebula I was given text prompt for rank and keys but only received 1 astral key. While I was asking for help in the server i opened the solar key that is given with the jade rank purchase. Then the server crashed as the key was spinning through the rewards. Once the server restarted I did not have the solar key or a reward from it either. Deathnight had helped me look through the logs that I had which was 17:09:00 on 7/31/22 but was unable to find anything. But if logs are still needed please let me know I will be happy to assist. I also have receipt for proof if needed as well. (Edit) after checking, was not awarded all player glows as stated in package description, ex light purple.

**Comment by HackuJacku** [comment]
@TheWeas - is this still an issue and if so, please DM me on discord (Hacko#0001).

**Comment by TheWeas** [comment]
It is still an issue, I have sent a friend request, just waiting for approval.

**Comment by HackuJacku** [comment]
> It is still an issue, I have sent a friend request, just waiting for approval.

What's your username please?

**Comment by TheWeas** [comment]
It is The_Weaz#6619

**Comment by HackuJacku** [comment]
Resolved via Discord
