### ISSUE TITLE
Cualan Form Gastrodon causes client crash upon trying to trade

### ISSUE THREAD

**Issue by TheNahgooyen** [NebulaMC-GG/Support#1696]
Title. Friend tried to trade one of the new Gastrodons over to me, immediately caused me, them, and another player nearby to all crash to desktop.

**Comment by Rasgnarok** [comment]
I'm missing the crash report, this is actually a Pixelmon bug that needs forwarding to Pixelmon itself, https://pixelmonmod.com/tracker.php?p=2

**Comment by CenizaRey** [comment]
Posted to Pixelmon's Bug Tracker, see here: https://pixelmonmod.com/tracker.php?p=2&t=18817
