### ISSUE TITLE
Won shiny modifier and it never went into my inventory

### ISSUE THREAD

**Issue by Heraderp** [NebulaMC-GG/Support#1697]
I had purchased a key and won a shiny modifier and it never went into my inventory and my inventory wasn't full on my account named kirbiru in the Orion server
![2022-07-31_16 45 54](https://user-images.githubusercontent.com/110368172/182069176-4df56ab4-bbd3-4ce5-b8d2-5ac1d18f0a6b.png)

**Comment by Rasgnarok** [comment]
Refunded your shiny modifier, thanks!
