### ISSUE TITLE
Chat/Hud Bug

### ISSUE THREAD

**Issue by CyberEnt1** [NebulaMC-GG/Support#1698]
Since the new update came out I ran into an issue. When I do /back my HUD and Chat move. It also happened to my friend.

![image](https://user-images.githubusercontent.com/109041979/182075245-9dd84e86-7020-4822-aa7a-94455e46edd9.png)

**Comment by CyberEnt1** [comment]
This doesn't happen on every /back, just a weird bug maybe a one-time thing?

**Comment by Lieren-HuntGhosts** [comment]
This means you don't have the latest Nebula Texture Pack for our server, as you can see in that gastrodon in the picture. 

You can download it in our #Intro channel in our discord. Here's an invitation to our discord and the texture pack itself:
https://discord.gg/3Upda7kP
https://cdn.discordapp.com/attachments/184691649778155521/1004792718070911056/NebulaMC-1.16.5-Resources-v1.0.7.zip
