### ISSUE TITLE
Dyeing a couch causes it to duplicate, creating an invisible entity that can destroy other blocks

### ISSUE THREAD

**Issue by DaikonXD** [NebulaMC-GG/Support#1700]
I decided to try dyeing my couches blue, and to my surprise I found them duplicating. Apparently someone else in chat had the same issue and it deleted some bells they had. Attached is 2 screenshots
![2022-08-01_23 23 46](https://user-images.githubusercontent.com/91439999/182291372-1c1e65ba-30f7-455c-9e7e-56e18e1ed0c2.png)
![2022-08-01_23 23 48](https://user-images.githubusercontent.com/91439999/182291378-f8245461-c387-4538-9cec-b9fce92761eb.png)
:

**Comment by Rasgnarok** [comment]
This needs to be forwarded to https://pixelmonmod.com/tracker.php?p=2, since this is a Pixelmon bug.

**Comment by Rasgnarok** [comment]
Has been forwarded, closing.
