### ISSUE TITLE
[Bingo] Issue with the hours left message

### ISSUE THREAD

**Issue by EzelBerbier** [NebulaMC-GG/Support#1701]
There is a visual issue with 1 hour left in the Bingo message, that appear when u use ./bingo and say u how many hours left to complete your bingo card. 

![unknown (2)](https://user-images.githubusercontent.com/108286828/182352106-23d1b08b-b584-4db7-93e0-9d2539aa96a6.png)

**Comment by Lieren-HuntGhosts** [comment]
This issue has already been solved. Issue can be closed
