### ISSUE TITLE
inconsistency on -10 level reducer obtained from Astral crates

### ISSUE THREAD

**Issue by toofuriouz** [NebulaMC-GG/Support#1710]
For the Item -10 level Reducer in the preview what item u could get page shows this:
![image](https://user-images.githubusercontent.com/85075804/183160128-b863c906-65fe-4761-832f-2c5deca9fb15.png)

And after you obtained it is this:
![image](https://user-images.githubusercontent.com/85075804/183160159-cb12a3a3-7dce-4dd5-bc67-95ef7255b3d2.png)

One indicates changes in IV and the latter indicateds changes in Levels, these 2 are different things and would like a look into it.
Personally feels like -10 Iv changes is a better choice since this give us some room to play with for hidden power

**Comment by HackuJacku** [comment]
Hello, thank you for reporting this. This is fixed as part of our upcoming crates update.
