### ISSUE TITLE
Pokedrops still dropping multiple drops for mons with multiple forms 

### ISSUE THREAD

**Issue by Deathnight7976** [NebulaMC-GG/Support#1716]
Pokemon such as Burmy, Wormadam, Lycanroc, Basculin, Castform and likely others still drop multiple sets of drops due to having multiple forms. 

Some screenies:
![Basculin](https://user-images.githubusercontent.com/17133410/184066759-a2e20e43-d509-48db-971e-7d5aa5079bcb.png)
![Burmy](https://user-images.githubusercontent.com/17133410/184066765-236f9706-af0e-464a-b06e-303dbc5e956a.png)
![Castform](https://user-images.githubusercontent.com/17133410/184066774-2eb65d05-e002-4bb6-b231-c8181c4aa48c.png)
![Lycanroc](https://user-images.githubusercontent.com/17133410/184066785-10f69548-460d-453a-bb4f-b14be62bcfac.png)

**Comment by Khrisstias** [comment]
My theory is that the stats files for all of these pokemon have not been properly refreshed when this issue was fixed in the mod. I have let Hacko know and will close once the files are fixed, thank you for the report c:

**Comment by CenizaRey** [comment]
Fixed every multi-form pokemon I could think of. There may still be a few stragglers, but hopefully the majority should be fixed. Thanks for the report!
