### ISSUE TITLE
Rotom spawning

### ISSUE THREAD

**Issue by Deathnight7976** [NebulaMC-GG/Support#1717]
After multiple hours of myself hunting with both Electric lures (3x) and lightning rod (5x) active I've yet to see a single Rotom spawn. 
Its of popular belief on Orion that Rotom spawns are bugged as I'm not the only one experiencing a lack of Rotoms.

**Comment by EzelBerbier** [comment]
On Atlas we have the same issue.

**Comment by CenizaRey** [comment]
This issue is due to be investigated tomorrow

**Comment by HackuJacku** [comment]
As per the latest #changelog in our Discord, this is now resolved. Thank you for reporting it :)
