### ISSUE TITLE
Vote Crate

### ISSUE THREAD

**Issue by Wolfman02** [NebulaMC-GG/Support#1718]
I rolled the mending book from a vote crate but didn't receive the book. It also said I received it from a cosmetic crate in the global chat.

**Comment by Khrisstias** [comment]
Hello! Were you ever refunded? If not, what is your IGN and server?

**Comment by Wolfman02** [comment]
I was refunded this was just to make the issue known.

**Comment by HackuJacku** [comment]
Thank you for reporting this issue, it has been fixed as part of our upcoming crates update :)
