### ISSUE TITLE
Oval Charm not working.

### ISSUE THREAD

**Issue by mosbuttpirate** [NebulaMC-GG/Support#1723]
Have Oval charm equipped and it does change the time required to produce an egg.
![image](https://user-images.githubusercontent.com/35019889/184460648-8df3d666-d80f-4c95-b5e0-ffe79d782ae3.png)

**Comment by Khrisstias** [comment]
Hihi!! I have confirmed this is a pixelmon bug and made a ticket for this: https://pixelmonmod.com/tracker.php?p=2&t=18897 Thank you very much! Closing
