### ISSUE TITLE
/item

### ISSUE THREAD

**Issue by Deathnight7976** [NebulaMC-GG/Support#1724]
/item no longer provides more details when hovering over the item in chat. It used to show lore/tooltips etc now it does not.

**Comment by HackuJacku** [comment]
@Deathnight7976, what happens if you use `/iteminfo`? The `/item` command acts like `/give` in 1.16.

**Comment by Deathnight7976** [comment]
My bad im dumb i meant [Item]

**Comment by HackuJacku** [comment]
Fixed from the next reboot.
