### ISSUE TITLE
issues with pokeloot dropping air

### ISSUE THREAD

**Issue by Beeaanis** [NebulaMC-GG/Support#1725]
![image](https://user-images.githubusercontent.com/111158992/184463232-e76458dd-e3aa-4b9f-b65f-ca6eb1dcb08a.png)
![image](https://user-images.githubusercontent.com/111158992/184463259-a3541110-52b8-476e-89be-0451cd2968ed.png)

I recently claimed a pokeloot on the map and did not get an item. the chat message says my inventory is full and air was dropped on the ground. My inventory was in fact, not full.

**Comment by CenizaRey** [comment]
This is fixed for next restart, thanks for the report!
