### ISSUE TITLE
Galarian Farfetch'd can't evolve into Sirfetch'd

### ISSUE THREAD

**Issue by AshOfTheCosmos** [NebulaMC-GG/Support#1726]
So, I tried doing the 3 crits in a single battle method to evolve my Galarian Farfetch'd and it didn't work. It may still be bugged. However, maybe for an easier way of evolving it, maybe have it hold a Black Belt and faint another pokemon, or an item along those lines. Just a suggestion though, to make it easier :)

**Comment by Khrisstias** [comment]
Hello! This is fixed pending restart. Thanks for the ticket!
