### ISSUE TITLE
Can't get on the server 

### ISSUE THREAD

**Issue by shenmueblake90** [NebulaMC-GG/Support#1727]
Won't let me log in, keeps saying Illegal package received, any ideas? This is my favorite Pixelmon server.

**Comment by MissElyri** [comment]
Could you place your latest logs here for us to look at?

**Comment by shenmueblake90** [comment]
I will first thing tomorrow

**Comment by shenmueblake90** [comment]
I'm not very good at computers,. It just says connection lost Illegal packet received, terminating connection

**Comment by HackuJacku** [comment]
@shenmueblake90 which Pixelmon version are you using? 

We have updated to Pixelmon 9.0.7 - if you're not already in our Discord, would recommend joining so you can remain updated with changes such as these.

**Comment by shenmueblake90** [comment]
Was still using 9.07 thank you so much, can you send me an invite to the discord?

**Comment by Deathnight7976** [comment]
Discord: https://discord.gg/B3XcYcR
