### ISSUE TITLE
/hunts giving discontinued item

### ISSUE THREAD

**Issue by Deathnight7976** [NebulaMC-GG/Support#1731]
I completed an ultimate hunt and was meant to receive 3x ranch upgrades. Since the update they no longer exist i was instead given air.
![ofc](https://user-images.githubusercontent.com/17133410/184471174-a1a87aed-03dd-4d6d-abd5-d9ebf69d787b.png)

Speculation:
Epic and Rare hunts may also have an issue since they are meant to give Golden/Silver hourglasses.

**Comment by HackuJacku** [comment]
@Deathnight7976 - what's your username and which server is this please?

**Comment by Deathnight7976** [comment]
Server: Orion
Ign: Deathnight7976

**Comment by HackuJacku** [comment]
I've put 1x Golden Hourglass in your inventory, @Deathnight7976. Enjoy :)
