### ISSUE TITLE
Bingo doesn't drop the hourglasses when completing a row and the full card

### ISSUE THREAD

**Issue by StrideMate** [NebulaMC-GG/Support#1732]
![Screenshot 2022-08-13 131033](https://user-images.githubusercontent.com/78794976/184471490-92c7eb54-6ab6-484e-93f1-4d5c92654f17.png)
![Screenshot 2022-08-13 131046](https://user-images.githubusercontent.com/78794976/184471492-c808ccd9-0a1f-4645-9efa-0b5a97ad023e.png)

**Comment by StrideMate** [comment]
To clarify, I don't want a refund for any of it just wanted to post it for it to be fixed whenever possible :D

**Comment by HackuJacku** [comment]
@StrideMate - this is now fixed. What is your username and server so we can refund you please?

**Comment by StrideMate** [comment]
@HackuJacku oh no sir, I don't want a refund all good :D Just was posting cause Elyri wanted me to so it's seen and fixed etc. Thank you though
