### ISSUE TITLE
"Illegal packet received"

### ISSUE THREAD

**Issue by SamyStar** [NebulaMC-GG/Support#1738]
So 4 days before, i could join normaly the server, but today i couldnt join because of "illegal packet received". I didnt download anything at all today, how can i fix this?

**Comment by HackuJacku** [comment]
@SamyStar - which Pixelmon version are you using please?

**Comment by SamyStar** [comment]
1.16.5

**Comment by HackuJacku** [comment]
> 1.16.5

This is the Minecraft version, not the Pixelmon version - that would be 9.0.6, 9.0.7, etc.

**Comment by SamyStar** [comment]
oh, its 9.0.6

**Comment by HackuJacku** [comment]
> oh, its 9.0.6

You need to update to 9.0.7. Once you have done this, your issue with be fixed. If you have any issues, please join our discord - discord.gg/nebulamc
