### ISSUE TITLE
Ultimate Boss Loot Pool 

### ISSUE THREAD

**Issue by Deathnight7976** [NebulaMC-GG/Support#1741]
I defeated an ultimate boss scizor and it dropped its normal drops +An Air.
Likely whatever the ultimate loot was has been deleted and instead now drops air.

Screenies:
![ScizorLoot](https://user-images.githubusercontent.com/17133410/184584572-f618b621-e807-4122-9e1d-5fdf31fe91af.jpg)
(The other drop not pictured was a razor claw I had already clicked before thinking to gather evidence.)
![Ultibossscizor2](https://user-images.githubusercontent.com/17133410/184584591-5a88f481-3190-4065-9294-aa1b2462aa1c.jpg)

IGN: Deathnight7976
Server: Orion

**Comment by CenizaRey** [comment]
This is likely a leftover Ranch Upgrade loot I missed, it will be fixed in the coming days. Sorry for the inconvenience, and thanks for your report! Keep an eye on #changelog
