### ISSUE TITLE
Opened a vote crate and didn't recieve item won

### ISSUE THREAD

**Issue by Lunar-DJ** [NebulaMC-GG/Support#1742]
Opened a vote crate last night and "won" a mending book. Didn't recieve it in my mostly-empty inventory, nor was it anywhere on the ground. 
Server is Orion
IGN is Lunar-DJ

**Comment by HackuJacku** [comment]
@Lunar-DJ - no one with the username `Lunar-DJ` has joined Orion. Can you provide your actual username please?

**Comment by Lunar-DJ** [comment]
Lunar_DJ is my username, my apologies

**Comment by HackuJacku** [comment]
> Lunar_DJ is my username, my apologies

Thank you! I have added a Mending Book to your inventory. You will have it the next time you log on :)
