### ISSUE TITLE
Custom pokedrops

### ISSUE THREAD

**Issue by Deathnight7976** [NebulaMC-GG/Support#1745]
Altered Pokedrops appear to have reverted back to "vanilla" Pixelmon drops.
Mons like Cufant who used to drop silver are now dropping iron, Duraludon is dropping Netherite again.

Seems to be network wide as seen on both Orion & Atlas

**Comment by CenizaRey** [comment]
Pixelmon changed the pokeloots json in 9.0.7 to be more efficiently formatted and versatile. I have begun reverting the drops back to what they were before but some will inevitably slip through the cracks and take longer to be detected. It’s not entirely vanilla. Thanks for the report!
