### ISSUE TITLE
Missing items from made rank

### ISSUE THREAD

**Issue by MillieClay** [NebulaMC-GG/Support#1753]
The items Silver hourglass, golden lense, and super repel are missing from the weekly kit in the jade rank

**Comment by CaptainTCovenant** [comment]
Need an IGN and a server to refund your items!

**Comment by CaptainTCovenant** [comment]
Items have been refunded!

**Comment by Doom1997** [comment]
Hi also did not receive those items with my jade rank. My ign: Doom2497, Server: Titan

**Comment by CaptainTCovenant** [comment]
Your items have been refunded, Doom!
