### ISSUE TITLE
[EggTimer] double message.

### ISSUE THREAD

**Issue by Vohras2** [NebulaMC-GG/Support#473]
Egg timer has a double message on the 4minute 30 second left mark.

[https://imgur.com/XYzs71D](url)

**Comment by Hiroku** [comment]
This should now be fixed, please retest if it's reproducible

**Comment by Vohras2** [comment]
Issue is still ongoing.
https://imgur.com/q4rVji6

**Comment by Rasgnarok** [comment]
@Vohras2 Does this still happen?

**Comment by Vohras2** [comment]
Yes, it does.

**Comment by Rasgnarok** [comment]
Closing, as we can't reproduce. Must be an edge case. We would need to know what Pokemon was hatched.

**Comment by Vohras2** [comment]
Just happened to me again when I was hatching a bunnelby.

**Comment by Vohras2** [comment]
Just happened once again on hatching Sableye and Mantine eggs.

**Comment by Hiroku** [comment]
After looking into this again, it's actually really bizarre and should be impossible if Pixelmon is doing a good job of this. Unsure if I'm going to be able to fix it

**Comment by Rasgnarok** [comment]
Closing, this will need re-testing on 1.16.5.
